package com.cafarovceyxun.anamuslim.utils.salah

/**
 * Namaz bələdçisinin dəlil mövzusu — `salah_evidence.topic`.
 *
 * Hər addımın, hər qaydanın öz mövzusu var: ekran addımın sabit mətnini koddan, hədis çıxarışlarını isə
 * bu açarla bazadan götürür. Admin çıxarışı tətbiqin içindən dəyişir, əlavə edir və silir — kod dəyişmir.
 *
 * ⚠️ [key] bazada saxlanır: **heç vaxt dəyişmə**, yoxsa həmin mövzunun dəlilləri qopar. Yeni mövzu
 * əlavə etmək təhlükəsizdir — köhnə tətbiq onu sadəcə göstərmir. [title] yalnız admin seçim siyahısıdır.
 *
 * Siyahı və ilkin dolğu eyni generatordan çıxıb (2026-10-04): Mərhələ 1 — 80 sətir, Mərhələ 2 — 106 sətir,
 * Mərhələ 3 — 153 sətir, Mərhələ 4 — 114 sətir; 2026-10-05 yoxlamasından sonra daha 12 sətir
 * (`tools/salah-content/fixes-2026-10-05/`).
 */
enum class SalahTopic(val key: String, val title: String) {
    WUDU1_MOUTH("wudu1_mouth", "Dəstəmaz, bir dəfə: ağız və burun"),
    WUDU1_FACE("wudu1_face", "Dəstəmaz, bir dəfə: üz"),
    WUDU1_RARM("wudu1_rarm", "Dəstəmaz, bir dəfə: sağ qol"),
    WUDU1_LARM("wudu1_larm", "Dəstəmaz, bir dəfə: sol qol"),
    WUDU1_HEAD("wudu1_head", "Dəstəmaz, bir dəfə: başa məsh"),
    WUDU1_RFOOT("wudu1_rfoot", "Dəstəmaz, bir dəfə: sağ ayaq"),
    WUDU1_LFOOT("wudu1_lfoot", "Dəstəmaz, bir dəfə: sol ayaq"),
    WUDU3_HANDS("wudu3_hands", "Dəstəmaz, tam forma: əllər"),
    WUDU3_MOUTH("wudu3_mouth", "Dəstəmaz, tam forma: ağız və burun"),
    WUDU3_FACE("wudu3_face", "Dəstəmaz, tam forma: üz"),
    WUDU3_ARMS("wudu3_arms", "Dəstəmaz, tam forma: qollar"),
    WUDU3_HEAD("wudu3_head", "Dəstəmaz, tam forma: başa məsh"),
    WUDU3_FEET("wudu3_feet", "Dəstəmaz, tam forma: ayaqlar"),
    WUDU_FORMS("wudu_forms", "Dəstəmaz: hər iki forma"),
    WUDU_DOUBT("wudu_doubt", "Dəstəmaz: qaz və şübhə"),
    WUDU_MADHY("wudu_madhy", "Dəstəmaz: məzi"),
    WUDU_MEAT("wudu_meat", "Dəstəmaz: ət yemək"),
    WUDU_MILK("wudu_milk", "Dəstəmaz: süd içmək"),
    WUDU_FOOD("wudu_food", "Dəstəmaz: ayaqyolundan sonra yemək"),
    WUDU_MISWAK("wudu_miswak", "Dəstəmaz: misvak"),
    WUDU_RIGHT("wudu_right", "Dəstəmaz: sağdan başlamaq"),
    WUDU_WATER("wudu_water", "Dəstəmaz: suyun miqdarı"),
    WUDU_MANY("wudu_many", "Dəstəmaz: bir dəstəmazla neçə namaz"),
    GHUSL_WET("ghusl_wet", "Qüsl: ehtilam"),
    GHUSL_FRIDAY("ghusl_friday", "Qüsl: cümə günü"),
    GHUSL_NOINZAL("ghusl_noinzal", "Qüsl: məni axmayanda"),
    GHUSL_HANDS("ghusl_hands", "Qüsl: əllər"),
    GHUSL_PRIVATE("ghusl_private", "Qüsl: övrət yeri"),
    GHUSL_WUDU("ghusl_wudu", "Qüsl: namaz dəstəmazı"),
    GHUSL_HAIR("ghusl_hair", "Qüsl: saçı isladmaq"),
    GHUSL_THREE("ghusl_three", "Qüsl: başa üç ovuc"),
    GHUSL_SIDES("ghusl_sides", "Qüsl: sağ, sol, orta"),
    GHUSL_BODY("ghusl_body", "Qüsl: bütün bədən"),
    GHUSL_WATER("ghusl_water", "Qüsl: suyun miqdarı"),
    GHUSL_SLEEP("ghusl_sleep", "Qüsl: cünubun yatması"),
    GHUSL_HAYD("ghusl_hayd", "Qüsl: heyzdən sonra"),
    TAHARAH_BELIEVER("taharah_believer", "Təharət: mömin nəcis olmur"),
    TAYAMMUM_STRIKE("tayammum_strike", "Təyəmmüm: ovucları yerə vurmaq"),
    TAYAMMUM_BLOW("tayammum_blow", "Təyəmmüm: üfürmək"),
    TAYAMMUM_FACE("tayammum_face", "Təyəmmüm: üzə məsh"),
    TAYAMMUM_HANDS("tayammum_hands", "Təyəmmüm: biləklərə məsh"),
    TAYAMMUM_ENOUGH("tayammum_enough", "Təyəmmüm: təmiz torpaq kifayətdir"),
    TAYAMMUM_NOWATER("tayammum_nowater", "Təyəmmüm: su olmayanda"),
    TAYAMMUM_JUNUB("tayammum_junub", "Təyəmmüm: cünub üçün"),
    TAYAMMUM_WALL("tayammum_wall", "Təyəmmüm: divarla"),
    TAYAMMUM_EARTH("tayammum_earth", "Təyəmmüm: yer üzü təmizdir"),
    KHUFF_WIPE("khuff_wipe", "Xuff: məsh"),
    KHUFF_TIME("khuff_time", "Xuff: müddət"),
    TOILET_DUA("toilet_dua", "Ayaqyolu: giriş duası"),
    TOILET_QIBLA("toilet_qibla", "Ayaqyolu: qiblə"),
    TOILET_HOUSE("toilet_house", "Ayaqyolu: İbn Ömərin damdan gördüyü"),
    TOILET_RIGHT("toilet_right", "Ayaqyolu: sağ əl"),
    TOILET_STONES("toilet_stones", "Ayaqyolu: daşla təmizlənmə"),
    TOILET_BONES("toilet_bones", "Ayaqyolu: peyin və sümük"),
    TOILET_STILL("toilet_still", "Ayaqyolu: durğun su"),
    TOILET_STANDING("toilet_standing", "Ayaqyolu: ayaq üstə"),
    NAJASA_BABY("najasa_baby", "Nəcasət: uşaq sidiyi"),
    NAJASA_FLOOR("najasa_floor", "Nəcasət: yerdəki sidik"),
    NAJASA_DOG("najasa_dog", "Nəcasət: itin yaladığı qab"),
    NAJASA_BLOOD("najasa_blood", "Nəcasət: heyz qanı"),
    NAJASA_MANI("najasa_mani", "Nəcasət: məni"),
    HAYD_PRAYER("hayd_prayer", "Heyz: namaz və oruc"),
    HAYD_QADA("hayd_qada", "Heyz: qəza"),
    HAYD_ISTIHADA("hayd_istihada", "Heyz: istihazə"),
    HAYD_DISCHARGE("hayd_discharge", "Heyz: rəngli ifrazat"),
    HAYD_EID("hayd_eid", "Heyz: bayram namazı"),

    // ---- Mərhələ 2: Əzan və namaz (2026-10-04, 106 sətir, `tools/salah-content/phase2/phase2_seed.py`) ----
    PRAYER_TEACH("prayer_teach", "Namaz: № 205 təlimi"),
    PRAYER_NIYYAH("prayer_niyyah", "Namaz: niyyət"),
    PRAYER_TAKBIR("prayer_takbir", "Namaz: təkbir"),
    PRAYER_HANDS("prayer_hands", "Namaz: sağ əl solun üstündə"),
    PRAYER_OPENING("prayer_opening", "Namaz: açılış duası"),
    PRAYER_READING("prayer_reading", "Namaz: qiraət"),
    PRAYER_RUKU_TAKBIR("prayer_ruku_takbir", "Namaz: rükuya təkbir"),
    PRAYER_RUKU("prayer_ruku", "Namaz: rüku"),
    PRAYER_RISE("prayer_rise", "Namaz: rükudan qalxmaq"),
    PRAYER_STANDING("prayer_standing", "Namaz: rükudan sonra qiyam"),
    PRAYER_SAJDA("prayer_sajda", "Namaz: səcdə"),
    PRAYER_BETWEEN("prayer_between", "Namaz: iki səcdə arası"),
    PRAYER_SAJDA2("prayer_sajda2", "Namaz: ikinci səcdə"),
    PRAYER_REST("prayer_rest", "Namaz: ikinci rükətə qalxmaq"),
    PRAYER_TASHAHHUD("prayer_tashahhud", "Namaz: təşəhhüd"),
    PRAYER_DUA("prayer_dua", "Namaz: təşəhhüddən sonra dua"),
    PRAYER_SALAM("prayer_salam", "Namaz: salam"),
    RAKAT_FAJR("rakat_fajr", "Rükət: Sübh"),
    RAKAT_ZUHR("rakat_zuhr", "Rükət: Zöhr"),
    RAKAT_FOUR("rakat_four", "Rükət: muqimə dörd"),
    RAKAT_MAGHRIB("rakat_maghrib", "Rükət: Məğrib"),
    READING_SILENT("reading_silent", "Qiraət: Zöhr və Əsr səssiz"),
    READING_FAJR("reading_fajr", "Qiraət: Fəcrdə eşidilirdi"),
    READING_MAGHRIB("reading_maghrib", "Qiraət: Məğribdə eşidilirdi"),
    READING_ISHA("reading_isha", "Qiraət: İşada eşidilirdi"),
    TIMES_BETWEEN("times_between", "Vaxtlar: Cibrilin iki günü"),
    TIMES_ONTIME("times_ontime", "Vaxtlar: vaxtında namaz"),
    TIMES_FORGOT("times_forgot", "Vaxtlar: unudulan namaz"),
    TIMES_RAKAH("times_rakah", "Vaxtlar: bir rükətə çatan"),
    TIMES_COOL("times_cool", "Vaxtlar: istidə Zöhr"),
    TIMES_ISHA("times_isha", "Vaxtlar: İşanı gecikdirmək"),
    TIMES_DELAYED("times_delayed", "Vaxtlar: namazı gecikdirən əmirlər"),
    TIMES_AFTER("times_after", "Vaxtlar: Sübhdən və Əsrdən sonra"),
    TIMES_SUN("times_sun", "Vaxtlar: Günəş doğarkən və batarkən"),
    TIMES_NOON("times_noon", "Vaxtlar: Günəş ortada"),
    TIMES_WOMEN("times_women", "Vaxtlar: qadınlar Sübhdə"),
    QIBLA_AYAH("qibla_ayah", "Qiblə: Bəqərə 144"),
    QIBLA_TURNED("qibla_turned", "Qiblə: namazda dönmək"),
    QIBLA_FARD("qibla_fard", "Qiblə: fərz qibləyə"),
    QIBLA_MOUNT("qibla_mount", "Qiblə: minik üstündə nafilə"),
    ADHAN_PAIRS("adhan_pairs", "Əzan: cüt, iqamə tək"),
    ADHAN_REPEAT("adhan_repeat", "Əzan: müəzzini təkrarlamaq"),
    ADHAN_BILAL("adhan_bilal", "Əzan: ilk müəzzin"),
    ADHAN_LOUD("adhan_loud", "Əzan: uca səs"),
    ADHAN_FAJR("adhan_fajr", "Əzan: Fəcrin iki əzanı"),
    ADHAN_RAIN("adhan_rain", "Əzan: soyuq və yağışda"),
    ADHAN_LEAVE("adhan_leave", "Əzan: sonra çıxıb getmək"),
    AFTER_TAKBIR("after_takbir", "Namazdan sonra: uca təkbir"),
    AFTER_SALAM("after_salam", "Namazdan sonra: Allahummə əntəs-salam"),
    AFTER_33("after_33", "Namazdan sonra: 33 + 33 + 33"),
    AFTER_TAHLIL("after_tahlil", "Namazdan sonra: təhlil"),
    AFTER_LEFT("after_left", "Namazdan sonra: hansı tərəfdən getmək"),
    KNOW_LIGHT("know_light", "Namazda: yüngül, amma tam"),
    KNOW_SKY("know_sky", "Namazda: göyə baxmaq"),
    KNOW_HIPS("know_hips", "Namazda: ixtisar"),
    KNOW_LOOK("know_look", "Namazda: boylanmaq"),
    KNOW_TALK("know_talk", "Namazda: danışmaq"),
    KNOW_SPIT("know_spit", "Namazda: tüpürmək"),
    KNOW_FOOD("know_food", "Namazda: yemək hazır ikən"),
    KNOW_SHOULDERS("know_shoulders", "Namazda: çiyinlər"),
    KNOW_SLEEPY("know_sleepy", "Namazda: mürgü"),
    KNOW_CHILD("know_child", "Namazda: uşaq qucaqda"),
    KNOW_PEBBLES("know_pebbles", "Namazda: daşları düzəltmək"),
    KNOW_TASBIH("know_tasbih", "Namazda: bir şey üz verəndə"),
    KNOW_ENTER("know_enter", "Namazda: məscidə girəndə"),
    KNOW_SUTRA("know_sutra", "Sütrə: nə boyda"),
    KNOW_PASS_SIN("know_pass_sin", "Sütrə: qarşıdan keçmək"),
    KNOW_PASS("know_pass", "Sütrə: keçmək istəyəni"),
    KNOW_CLAP("know_clap", "Namazda: qadınlar əl çırpır"),
    KNOW_MOSQUE("know_mosque", "Namazda: qadınlar məsciddə"),

    // ---- Mərhələ 3: Camaat və xüsusi namazlar (2026-10-04, 153 sətir, `tools/salah-content/phase3/phase3_seed.py`) ----
    JAMAAH_25("jamaah_25", "Camaat: iyirmi beş dərəcə"),
    JAMAAH_STEPS("jamaah_steps", "Camaat: məscidə addımlar"),
    JAMAAH_ISHA_FAJR("jamaah_isha_fajr", "Camaat: İşa və Sübh"),
    JAMAAH_FIRST_ROW("jamaah_first_row", "Camaat: əzan və ilk səf"),
    JAMAAH_ABSENT("jamaah_absent", "Camaat: geri qalmaq"),
    IMAM_QURAN("imam_quran", "İmam: Quranı ən çox bilən"),
    IMAM_OLDEST("imam_oldest", "İmam: yaşıdlarda ən böyüyü"),
    IMAM_LIKE_ME("imam_like_me", "İmam: Nəbi kimi qılmaq"),
    FOLLOW_IMAM("follow_imam", "İmama tabe: ona uyulsun deyə"),
    FOLLOW_AMIN("follow_amin", "İmama tabe: Amin"),
    FOLLOW_RABBANA("follow_rabbana", "İmama tabe: Rabbənə ləkəl-həmd"),
    FOLLOW_BEFORE("follow_before", "İmama tabe: imamdan qabaq"),
    FOLLOW_AFTER("follow_after", "İmama tabe: imamdan sonra səcdə"),
    FOLLOW_SITTING("follow_sitting", "İmama tabe: oturaraq qılan imam"),
    FOLLOW_COMPLETE("follow_complete", "İmama tabe: rüku və səcdəni tamamlamaq"),
    LATE_WALK("late_walk", "Gec gələn: tələsmədən"),
    LATE_STAND("late_stand", "Gec gələn: imamı görməmiş durmamaq"),
    LATE_IQAMA("late_iqama", "Gec gələn: iqamədən sonra başqa namaz"),
    LATE_HAMD("late_hamd", "Gec gələn: səfə qoşulanın həmdi"),
    LIGHT_WEAK("light_weak", "İmam yüngül qıldırsın"),
    LIGHT_ANGRY("light_angry", "İmam: insanları uzaqlaşdırmaq"),
    LIGHT_MUADH("light_muadh", "İmam: Muaza tövsiyə"),
    LIGHT_SHORT("light_short", "İmam: xəfif, amma tam"),
    QUNUT_AFTER("qunut_after", "Qunut: rükudan sonra"),
    QUNUT_WHEN("qunut_when", "Qunut: kimin üçün"),
    QUNUT_MONTH("qunut_month", "Qunut: bir ay, sonra tərk"),
    QUNUT_AYAH("qunut_ayah", "Qunut: Ali-İmran 128"),
    QUNUT_ABUHURAYRA("qunut_abuhurayra", "Qunut: Əbu Hureyrə"),
    ROWS_OR("rows_or", "Səflər: ya düzəldərsiniz"),
    ROWS_STRAIGHT("rows_straight", "Səflər: ox kimi düz"),
    ROWS_TIGHT("rows_tight", "Səflər: sıxlaşmaq"),
    ROWS_GAPS("rows_gaps", "Səflər: boşluq qoymamaq"),
    ROWS_SEES("rows_sees", "Səflər: arxadan görürəm"),
    SEAT_ONE("seat_one", "Səflər: bir kişi sağda"),
    SEAT_ONE_WOMAN("seat_one_woman", "Səflər: kişi və qadın"),
    SEAT_TWO_WOMEN("seat_two_women", "Səflər: kişi və iki qadın"),
    SEAT_TWO_BOYS("seat_two_boys", "Səflər: iki uşaq və qadın"),
    ROWS_WOMEN("rows_women", "Səflər: qadınlar arxada"),
    JUMUAH_DAY("jumuah_day", "Cümə: bu günə hidayət"),
    JUMUAH_GHUSL("jumuah_ghusl", "Cümə: qüsl"),
    JUMUAH_PREP("jumuah_prep", "Cümə: təmizlik, yağ, ətir"),
    JUMUAH_EARLY("jumuah_early", "Cümə: erkən getmək"),
    JUMUAH_NO_SPLIT("jumuah_no_split", "Cümə: iki nəfərin arasını ayırmamaq"),
    JUMUAH_PRAY("jumuah_pray", "Cümə: gəlib namaz qılmaq"),
    JUMUAH_QUIET("jumuah_quiet", "Cümə: xütbədə susmaq"),
    JUMUAH_ADHAN("jumuah_adhan", "Cümə: əzan"),
    JUMUAH_KHUTBAH("jumuah_khutbah", "Cümə: iki xütbə"),
    JUMUAH_RAKAH("jumuah_rakah", "Cümə: iki rükət və surələr"),
    JUMUAH_HOME("jumuah_home", "Cümə: sonra evdə iki rükət"),
    JUMUAH_TIME("jumuah_time", "Cümə: vaxtı"),
    JUMUAH_HOUR("jumuah_hour", "Cümə: duanın qəbul olduğu saat"),
    JUMUAH_GHUSL_WHY("jumuah_ghusl_why", "Cümə: qüslün səbəbi"),
    JUMUAH_TAHIYYA("jumuah_tahiyya", "Cümə: xütbədə gələn"),
    JUMUAH_FAJR("jumuah_fajr", "Cümə: Sübhdə qiraət"),
    JUMUAH_CARAVAN("jumuah_caravan", "Cümə: xütbəni qoyub getmək"),
    SAFAR_SADAQA("safar_sadaqa", "Səfər: qəsr sədəqədir"),
    SAFAR_TWO("safar_two", "Səfər: namaz iki rükət qaldı"),
    SAFAR_TOWN("safar_town", "Səfər: şəhərdən çıxanda"),
    SAFAR_SAFE("safar_safe", "Səfər: əmin-amanlıqda da"),
    SAFAR_ZUHR_ASR("safar_zuhr_asr", "Səfər: Zöhr və Əsr"),
    SAFAR_MAGHRIB_ISHA("safar_maghrib_isha", "Səfər: Məğrib və İşa"),
    SAFAR_ARAFAH("safar_arafah", "Səfər: Ərəfatda Zöhr və Əsr"),
    SAFAR_HADAR("safar_hadar", "Səfər: şəhərdə birləşdirmək"),
    SAFAR_NO_SUNNAH("safar_no_sunnah", "Səfər: sünnət qılınmır"),
    SAFAR_MINA("safar_mina", "Səfər: mukim imamın arxasında"),
    EID_DAYS("eid_days", "Bayram: iki gün"),
    EID_MUSALLA("eid_musalla", "Bayram: musalləyə çıxmaq"),
    EID_NO_ADHAN("eid_no_adhan", "Bayram: əzan və iqamə yoxdur"),
    EID_TWO("eid_two", "Bayram: iki rükət"),
    EID_KHUTBAH("eid_khutbah", "Bayram: namazdan sonra xütbə"),
    EID_SADAQA("eid_sadaqa", "Bayram: sədəqəyə çağırış"),
    EID_FIRST("eid_first", "Bayram: namaz xütbədən əvvəl"),
    EID_MARWAN("eid_marwan", "Bayram: xütbəni qabağa keçirmək"),
    EID_WOMEN("eid_women", "Bayram: qadınlar çıxsın"),
    EID_WOMEN_SADAQA("eid_women_sadaqa", "Bayram: qadınların sədəqəsi"),
    ISTISQA_ASK("istisqa_ask", "İstisqa: quraqlıq ili"),
    ISTISQA_OUT("istisqa_out", "İstisqa: musalləyə çıxmaq"),
    ISTISQA_BACK("istisqa_back", "İstisqa: qibləyə dönüb dua"),
    ISTISQA_HANDS("istisqa_hands", "İstisqa: əllərin qaldırılması"),
    ISTISQA_PRAY("istisqa_pray", "İstisqa: iki rükət uca səslə"),
    ISTISQA_JUMUAH("istisqa_jumuah", "İstisqa: Cümə xütbəsində"),
    ISTISQA_DUA("istisqa_dua", "İstisqa: dualar"),
    ISTISQA_ONLY("istisqa_only", "Dua: istisqada əllər"),
    ISTISQA_OTHER("istisqa_other", "Dua: başqa dualarda əllər"),
    KUSUF_SIGNS("kusuf_signs", "Küsuf: iki ayət"),
    KUSUF_HOW("kusuf_how", "Küsuf: qılınışı"),
    KUSUF_UNTIL("kusuf_until", "Küsuf: açılanadək namaz"),
    KUSUF_DO("kusuf_do", "Küsuf: dua, təkbir, sədəqə"),
    KUSUF_ZIKR("kusuf_zikr", "Küsuf: zikr"),
    KUSUF_ITQ("kusuf_itq", "Küsuf: qul azad etmək"),
    KUSUF_KHUTBAH("kusuf_khutbah", "Küsuf: namazdan sonra xütbə"),
    KUSUF_WOMEN("kusuf_women", "Küsuf: qadınlar namazda"),
    KHAWF_1("khawf_1", "Qorxu: 1 + 1"),
    KHAWF_2("khawf_2", "Qorxu: növbəli keşik"),
    KHAWF_3("khawf_3", "Qorxu: düşmən qiblədə"),
    KHAWF_4("khawf_4", "Qorxu: imam dörd"),
    KHAWF_5("khawf_5", "Qorxu: hər dəstə bir"),
    KHAWF_SEVERE("khawf_severe", "Qorxu: çox şiddətli olanda"),

    // ---- Mərhələ 4: Nafilə və cənazə (2026-10-04, 114 sətir, `tools/salah-content/phase4/phase4_seed.py`) ----
    SUNNAH_12("sunnah_12", "Sünnət: on iki rükətin fəziləti"),
    SUNNAH_TEN("sunnah_ten", "Sünnət: İbn Ömərin on rükəti"),
    SUNNAH_BETWEEN("sunnah_between", "Sünnət: hər əzan ilə iqamə arası"),
    FAJR_NEVER("fajr_never", "Fəcrin iki rükəti: heç tərk etmədi"),
    FAJR_EAGER("fajr_eager", "Fəcrin iki rükəti: tələsərdi"),
    FAJR_LIGHT("fajr_light", "Fəcrin iki rükəti: xəfif"),
    FAJR_READING("fajr_reading", "Fəcrin iki rükəti: nə oxunur"),
    FAJR_LIE("fajr_lie", "Fəcrin iki rükəti: sonra uzanmaq"),
    MAGHRIB_BEFORE("maghrib_before", "Sünnət: Məğribdən əvvəl iki rükət"),
    SUNNAH_NAHY("sunnah_nahy", "Sünnət: Sübh və Əsrdən sonra qadağa"),
    SUNNAH_ASR_TWO("sunnah_asr_two", "Sünnət: Əsrdən sonrakı iki rükət"),
    DUHA_WILL("duha_will", "Duha: vəsiyyət"),
    DUHA_EIGHT("duha_eight", "Duha: fəth günü səkkiz rükət"),
    DUHA_FULL("duha_full", "Duha: xəfif, amma tam"),
    DUHA_ANAS("duha_anas", "Duha: Ənəsin sözü"),
    DUHA_AISHA("duha_aisha", "Duha: Aişənin sözü"),
    DUHA_IBN_UMAR("duha_ibn_umar", "Duha: İbn Ömərin sözü"),
    NAFL_RETURN("nafl_return", "Nafilə: səfərdən qayıdanda"),
    NAFL_BILAL("nafl_bilal", "Nafilə: dəstəmazdan sonra"),
    NAFL_HOME("nafl_home", "Nafilə: evdə qılmaq"),
    NAFL_ABLE("nafl_able", "Nafilə: az da olsa davamlı"),
    NAFL_TIRED("nafl_tired", "Nafilə: yorulanda oturmaq"),
    NAFL_WOMEN("nafl_women", "Nafilə: qadınlar üçün"),
    NIGHT_DAWUD("night_dawud", "Gecə: Davudun namazı"),
    NIGHT_KNOTS("night_knots", "Gecə: şeytanın üç düyünü"),
    NIGHT_SLEPT("night_slept", "Gecə: səhərədək yatan"),
    NIGHT_RIGHTS("night_rights", "Gecə: özünü yormamaq"),
    NIGHT_TIME("night_time", "Gecə: nə vaxt qalxardı"),
    WITR_ANY("witr_any", "Vitr: gecənin hər vaxtında"),
    NIGHT_SLEEP_AFTER("night_sleep_after", "Gecə: vitrdən sonra yatmaq"),
    NIGHT_TWO_TWO("night_two_two", "Gecə: iki-iki"),
    WITR_ONE("witr_one", "Vitr: bir rükət, sonuncu"),
    NIGHT_FORM_A("night_form_a", "Gecə: 4 + 4 + 3"),
    NIGHT_FORM_B("night_form_b", "Gecə: hər iki rükətdə salam"),
    NIGHT_FORM_C("night_form_c", "Gecə: Fəcrin sünnəti ilə on üç"),
    NIGHT_FORM_D("night_form_d", "Gecə: Zeydin izlədiyi on üç"),
    NIGHT_FORM_E("night_form_e", "Gecə: İbn Abbasın gecələri"),
    NIGHT_EYES("night_eyes", "Gecə: gözlərim yatır, qəlbim yox"),
    NIGHT_WAKE_FACE("night_wake_face", "Gecə: qalxanda üzü silmək"),
    NIGHT_WAKE_QURAN("night_wake_quran", "Gecə: Ali-İmranın sonu"),
    NIGHT_WAKE_MISWAK("night_wake_miswak", "Gecə: misvak və dəstəmaz"),
    NIGHT_DUA_TAHAJJUD("night_dua_tahajjud", "Gecə duası: təhəccüd"),
    NIGHT_DUA_NUR("night_dua_nur", "Gecə duası: nur"),
    NIGHT_DUA_SAJDA("night_dua_sajda", "Gecə duası: səcdədə"),
    NIGHT_RIGHT_SIDE("night_right_side", "Gecə: tək qoşulan sağda"),
    NIGHT_RAMADAN("night_ramadan", "Gecə: Ramazanda camaatla"),
    NIGHT_TARTIL("night_tartil", "Gecə: tərtil"),
    NIGHT_SITTING("night_sitting", "Gecə: oturaraq qılmaq"),
    NIGHT_LONG_SAJDA("night_long_sajda", "Gecə: uzun səcdə"),
    NIGHT_WOMEN("night_women", "Gecə: qadınlar üçün"),
    SAHW_SHAYTAN("sahw_shaytan", "Səhv: şeytanın vəsvəsəsi"),
    SAHW_SIT("sahw_sit", "Səhv: oturaraq iki səcdə"),
    SAHW_YAQIN("sahw_yaqin", "Səhv: yəqin üzərində, salamdan əvvəl"),
    SAHW_TAHARRI("sahw_taharri", "Səhv: doğrunu araşdırmaq, salamdan sonra"),
    SAHW_EXTRA("sahw_extra", "Səhv: beş rükət qılmaq"),
    SAHW_LESS("sahw_less", "Səhv: tez salam vermək"),
    SAHW_TASHAHHUD("sahw_tashahhud", "Səhv: birinci təşəhhüdü unutmaq"),
    TILAWAH_OUT("tilawah_out", "Tilavət: namazdan xaric"),
    TILAWAH_NAJM("tilawah_najm", "Tilavət: Nəcm"),
    TILAWAH_INSHIQAQ("tilawah_inshiqaq", "Tilavət: İnşiqaq"),
    TILAWAH_ALAQ("tilawah_alaq", "Tilavət: Aləq"),
    JANAZAH_QIRAT("janazah_qirat", "Cənazə: qirat"),
    JANAZAH_WASH("janazah_wash", "Cənazə: yumaq"),
    JANAZAH_WASH_RIGHT("janazah_wash_right", "Cənazə: sağdan başlamaq"),
    JANAZAH_SHROUD("janazah_shroud", "Cənazə: kəfən"),
    JANAZAH_HAIR("janazah_hair", "Cənazə: qadının saçı"),
    JANAZAH_ROWS("janazah_rows", "Cənazə: musallə və səflər"),
    JANAZAH_TAKBIR("janazah_takbir", "Cənazə: dörd təkbir"),
    JANAZAH_FATIHA("janazah_fatiha", "Cənazə: Fatihə"),
    JANAZAH_ISTIGHFAR("janazah_istighfar", "Cənazə: bağışlanma diləmək"),
    JANAZAH_GRAVE("janazah_grave", "Cənazə: qəbrə namaz"),
    JANAZAH_ABROAD("janazah_abroad", "Cənazə: uzaqda ölənə"),
    JANAZAH_MARTYRS("janazah_martyrs", "Cənazə: şəhidlərə"),
    JANAZAH_DEBT("janazah_debt", "Cənazə: borcluya"),
    JANAZAH_MUNAFIQ("janazah_munafiq", "Cənazə: münafiqə"),
    JANAZAH_GRAVES("janazah_graves", "Cənazə: qəbirlərin üstündə"),
    JANAZAH_PLACE("janazah_place", "Cənazə: harada qoyulur"),
    JANAZAH_WOMEN("janazah_women", "Cənazə: qadınlar üçün"),
    ;

    companion object {
        fun of(key: String): SalahTopic? = entries.firstOrNull { it.key == key }
    }
}
