package com.cafarovceyxun.anamuslim.utils.salah

/**
 * Namaz bələdçisinin dəlil mövzusu — `salah_evidence.topic`.
 *
 * Hər addımın, hər qaydanın öz mövzusu var: ekran addımın sabit mətnini koddan, hədis çıxarışlarını isə
 * bu açarla bazadan götürür. Admin çıxarışı tətbiqin içindən dəyişir, əlavə edir və silir — kod dəyişmir.
 *
 * ⚠️ [key] bazada saxlanır: **heç vaxt dəyişmə**, yoxsa həmin mövzunun dəlilləri qopar. Yeni mövzu
 * əlavə etmək təhlükəsizdir — köhnə tətbiq onu sadəcə göstərmir. [title] yalnız admin seçim siyahısıdır.
 *
 * Siyahı və ilkin dolğu eyni generatordan çıxıb (2026-10-04): Mərhələ 1 — 80 sətir, Mərhələ 2 — 106 sətir.
 */
enum class SalahTopic(val key: String, val title: String) {
    WUDU1_MOUTH("wudu1_mouth", "Dəstəmaz, bir dəfə: ağız və burun"),
    WUDU1_FACE("wudu1_face", "Dəstəmaz, bir dəfə: üz"),
    WUDU1_RARM("wudu1_rarm", "Dəstəmaz, bir dəfə: sağ qol"),
    WUDU1_LARM("wudu1_larm", "Dəstəmaz, bir dəfə: sol qol"),
    WUDU1_HEAD("wudu1_head", "Dəstəmaz, bir dəfə: başa məsh"),
    WUDU1_RFOOT("wudu1_rfoot", "Dəstəmaz, bir dəfə: sağ ayaq"),
    WUDU1_LFOOT("wudu1_lfoot", "Dəstəmaz, bir dəfə: sol ayaq"),
    WUDU3_HANDS("wudu3_hands", "Dəstəmaz, tam forma: əllər"),
    WUDU3_MOUTH("wudu3_mouth", "Dəstəmaz, tam forma: ağız və burun"),
    WUDU3_FACE("wudu3_face", "Dəstəmaz, tam forma: üz"),
    WUDU3_ARMS("wudu3_arms", "Dəstəmaz, tam forma: qollar"),
    WUDU3_HEAD("wudu3_head", "Dəstəmaz, tam forma: başa məsh"),
    WUDU3_FEET("wudu3_feet", "Dəstəmaz, tam forma: ayaqlar"),
    WUDU_FORMS("wudu_forms", "Dəstəmaz: hər iki forma"),
    WUDU_DOUBT("wudu_doubt", "Dəstəmaz: qaz və şübhə"),
    WUDU_MADHY("wudu_madhy", "Dəstəmaz: məzi"),
    WUDU_MEAT("wudu_meat", "Dəstəmaz: ət yemək"),
    WUDU_MILK("wudu_milk", "Dəstəmaz: süd içmək"),
    WUDU_FOOD("wudu_food", "Dəstəmaz: ayaqyolundan sonra yemək"),
    WUDU_MISWAK("wudu_miswak", "Dəstəmaz: misvak"),
    WUDU_RIGHT("wudu_right", "Dəstəmaz: sağdan başlamaq"),
    WUDU_WATER("wudu_water", "Dəstəmaz: suyun miqdarı"),
    WUDU_MANY("wudu_many", "Dəstəmaz: bir dəstəmazla neçə namaz"),
    GHUSL_WET("ghusl_wet", "Qüsl: ehtilam"),
    GHUSL_FRIDAY("ghusl_friday", "Qüsl: cümə günü"),
    GHUSL_NOINZAL("ghusl_noinzal", "Qüsl: məni axmayanda"),
    GHUSL_HANDS("ghusl_hands", "Qüsl: əllər"),
    GHUSL_PRIVATE("ghusl_private", "Qüsl: övrət yeri"),
    GHUSL_WUDU("ghusl_wudu", "Qüsl: namaz dəstəmazı"),
    GHUSL_HAIR("ghusl_hair", "Qüsl: saçı isladmaq"),
    GHUSL_THREE("ghusl_three", "Qüsl: başa üç ovuc"),
    GHUSL_SIDES("ghusl_sides", "Qüsl: sağ, sol, orta"),
    GHUSL_BODY("ghusl_body", "Qüsl: bütün bədən"),
    GHUSL_WATER("ghusl_water", "Qüsl: suyun miqdarı"),
    GHUSL_SLEEP("ghusl_sleep", "Qüsl: cünubun yatması"),
    GHUSL_HAYD("ghusl_hayd", "Qüsl: heyzdən sonra"),
    TAHARAH_BELIEVER("taharah_believer", "Təharət: mömin nəcis olmur"),
    TAYAMMUM_STRIKE("tayammum_strike", "Təyəmmüm: ovucları yerə vurmaq"),
    TAYAMMUM_BLOW("tayammum_blow", "Təyəmmüm: üfürmək"),
    TAYAMMUM_FACE("tayammum_face", "Təyəmmüm: üzə məsh"),
    TAYAMMUM_HANDS("tayammum_hands", "Təyəmmüm: biləklərə məsh"),
    TAYAMMUM_ENOUGH("tayammum_enough", "Təyəmmüm: təmiz torpaq kifayətdir"),
    TAYAMMUM_NOWATER("tayammum_nowater", "Təyəmmüm: su olmayanda"),
    TAYAMMUM_JUNUB("tayammum_junub", "Təyəmmüm: cünub üçün"),
    TAYAMMUM_WALL("tayammum_wall", "Təyəmmüm: divarla"),
    TAYAMMUM_EARTH("tayammum_earth", "Təyəmmüm: yer üzü təmizdir"),
    KHUFF_WIPE("khuff_wipe", "Xuff: məsh"),
    KHUFF_TIME("khuff_time", "Xuff: müddət"),
    TOILET_DUA("toilet_dua", "Ayaqyolu: giriş duası"),
    TOILET_QIBLA("toilet_qibla", "Ayaqyolu: qiblə"),
    TOILET_HOUSE("toilet_house", "Ayaqyolu: bina içində"),
    TOILET_RIGHT("toilet_right", "Ayaqyolu: sağ əl"),
    TOILET_STONES("toilet_stones", "Ayaqyolu: daşla təmizlənmə"),
    TOILET_BONES("toilet_bones", "Ayaqyolu: peyin və sümük"),
    TOILET_STILL("toilet_still", "Ayaqyolu: durğun su"),
    TOILET_STANDING("toilet_standing", "Ayaqyolu: ayaq üstə"),
    NAJASA_BABY("najasa_baby", "Nəcasət: uşaq sidiyi"),
    NAJASA_FLOOR("najasa_floor", "Nəcasət: yerdəki sidik"),
    NAJASA_DOG("najasa_dog", "Nəcasət: itin yaladığı qab"),
    NAJASA_BLOOD("najasa_blood", "Nəcasət: heyz qanı"),
    NAJASA_MANI("najasa_mani", "Nəcasət: məni"),
    HAYD_PRAYER("hayd_prayer", "Heyz: namaz və oruc"),
    HAYD_QADA("hayd_qada", "Heyz: qəza"),
    HAYD_ISTIHADA("hayd_istihada", "Heyz: istihazə"),
    HAYD_DISCHARGE("hayd_discharge", "Heyz: rəngli ifrazat"),
    HAYD_EID("hayd_eid", "Heyz: bayram namazı"),

    // ---- Mərhələ 2: Əzan və namaz (2026-10-04, 106 sətir, `tools/salah-content/phase2/phase2_seed.py`) ----
    PRAYER_TEACH("prayer_teach", "Namaz: № 205 təlimi"),
    PRAYER_NIYYAH("prayer_niyyah", "Namaz: niyyət"),
    PRAYER_TAKBIR("prayer_takbir", "Namaz: təkbir"),
    PRAYER_HANDS("prayer_hands", "Namaz: əllər sinədə"),
    PRAYER_OPENING("prayer_opening", "Namaz: açılış duası"),
    PRAYER_READING("prayer_reading", "Namaz: qiraət"),
    PRAYER_RUKU_TAKBIR("prayer_ruku_takbir", "Namaz: rükuya təkbir"),
    PRAYER_RUKU("prayer_ruku", "Namaz: rüku"),
    PRAYER_RISE("prayer_rise", "Namaz: rükudan qalxmaq"),
    PRAYER_STANDING("prayer_standing", "Namaz: rükudan sonra qiyam"),
    PRAYER_SAJDA("prayer_sajda", "Namaz: səcdə"),
    PRAYER_BETWEEN("prayer_between", "Namaz: iki səcdə arası"),
    PRAYER_SAJDA2("prayer_sajda2", "Namaz: ikinci səcdə"),
    PRAYER_REST("prayer_rest", "Namaz: ikinci rükətə qalxmaq"),
    PRAYER_TASHAHHUD("prayer_tashahhud", "Namaz: təşəhhüd"),
    PRAYER_DUA("prayer_dua", "Namaz: təşəhhüddən sonra dua"),
    PRAYER_SALAM("prayer_salam", "Namaz: salam"),
    RAKAT_FAJR("rakat_fajr", "Rükət: Sübh"),
    RAKAT_ZUHR("rakat_zuhr", "Rükət: Zöhr"),
    RAKAT_FOUR("rakat_four", "Rükət: muqimə dörd"),
    RAKAT_MAGHRIB("rakat_maghrib", "Rükət: Məğrib"),
    READING_SILENT("reading_silent", "Qiraət: Zöhr və Əsr səssiz"),
    READING_FAJR("reading_fajr", "Qiraət: Fəcrdə eşidilirdi"),
    READING_MAGHRIB("reading_maghrib", "Qiraət: Məğribdə eşidilirdi"),
    TIMES_BETWEEN("times_between", "Vaxtlar: Cibrilin iki günü"),
    TIMES_ONTIME("times_ontime", "Vaxtlar: vaxtında namaz"),
    TIMES_FORGOT("times_forgot", "Vaxtlar: unudulan namaz"),
    TIMES_RAKAH("times_rakah", "Vaxtlar: bir rükətə çatan"),
    TIMES_COOL("times_cool", "Vaxtlar: istidə Zöhr"),
    TIMES_ISHA("times_isha", "Vaxtlar: İşanı gecikdirmək"),
    TIMES_AFTER("times_after", "Vaxtlar: Sübhdən və Əsrdən sonra"),
    TIMES_SUN("times_sun", "Vaxtlar: Günəş doğarkən və batarkən"),
    TIMES_NOON("times_noon", "Vaxtlar: Günəş ortada"),
    TIMES_WOMEN("times_women", "Vaxtlar: qadınlar Sübhdə"),
    QIBLA_AYAH("qibla_ayah", "Qiblə: Bəqərə 144"),
    QIBLA_TURNED("qibla_turned", "Qiblə: namazda dönmək"),
    QIBLA_FARD("qibla_fard", "Qiblə: fərz qibləyə"),
    QIBLA_MOUNT("qibla_mount", "Qiblə: minik üstündə nafilə"),
    ADHAN_PAIRS("adhan_pairs", "Əzan: cüt, iqamə tək"),
    ADHAN_REPEAT("adhan_repeat", "Əzan: müəzzini təkrarlamaq"),
    ADHAN_BILAL("adhan_bilal", "Əzan: ilk müəzzin"),
    ADHAN_LOUD("adhan_loud", "Əzan: uca səs"),
    ADHAN_FAJR("adhan_fajr", "Əzan: Fəcrin iki əzanı"),
    ADHAN_RAIN("adhan_rain", "Əzan: soyuq və yağışda"),
    ADHAN_LEAVE("adhan_leave", "Əzan: sonra çıxıb getmək"),
    AFTER_TAKBIR("after_takbir", "Namazdan sonra: uca təkbir"),
    AFTER_SALAM("after_salam", "Namazdan sonra: Allahummə əntəs-salam"),
    AFTER_33("after_33", "Namazdan sonra: 33 + 33 + 33"),
    AFTER_TAHLIL("after_tahlil", "Namazdan sonra: təhlil"),
    AFTER_LEFT("after_left", "Namazdan sonra: hansı tərəfdən getmək"),
    KNOW_LIGHT("know_light", "Namazda: yüngül, amma tam"),
    KNOW_SKY("know_sky", "Namazda: göyə baxmaq"),
    KNOW_HIPS("know_hips", "Namazda: ixtisar"),
    KNOW_LOOK("know_look", "Namazda: boylanmaq"),
    KNOW_TALK("know_talk", "Namazda: danışmaq"),
    KNOW_SPIT("know_spit", "Namazda: tüpürmək"),
    KNOW_FOOD("know_food", "Namazda: yemək hazır ikən"),
    KNOW_SHOULDERS("know_shoulders", "Namazda: çiyinlər"),
    KNOW_SLEEPY("know_sleepy", "Namazda: mürgü"),
    KNOW_CHILD("know_child", "Namazda: uşaq qucaqda"),
    KNOW_PEBBLES("know_pebbles", "Namazda: daşları düzəltmək"),
    KNOW_TASBIH("know_tasbih", "Namazda: bir şey üz verəndə"),
    KNOW_ENTER("know_enter", "Namazda: məscidə girəndə"),
    KNOW_SUTRA("know_sutra", "Sütrə: nə boyda"),
    KNOW_PASS_SIN("know_pass_sin", "Sütrə: qarşıdan keçmək"),
    KNOW_PASS("know_pass", "Sütrə: keçmək istəyəni"),
    KNOW_CLAP("know_clap", "Namazda: qadınlar əl çırpır"),
    KNOW_MOSQUE("know_mosque", "Namazda: qadınlar məsciddə"),
    ;

    companion object {
        fun of(key: String): SalahTopic? = entries.firstOrNull { it.key == key }
    }
}
