package com.cafarovceyxun.anamuslim.api

import com.cafarovceyxun.anamuslim.api.models.ResourcesVersions
import com.cafarovceyxun.anamuslim.api.models.wbw.AvailableWbwInfoModel
import io.ktor.client.request.get
import io.ktor.client.statement.bodyAsText

/**
 * Inventory endpoints served from the active download-source mirror (gh-proxy / raw / jsdelivr).
 * [baseUrl] is updated by the app's `DownloadSourceUtils` when the user switches mirror.
 *
 * Typed responses are decoded explicitly from text (not via ContentNegotiation) to mirror the
 * previous Retrofit converter, which deserialized regardless of the server `Content-Type`
 * (mirrors often serve `.json` as `text/plain`).
 */
object GithubApi {
    var baseUrl: String = ApiConfig.GH_RAW_BASE_URL

    private fun url(path: String) = baseUrl.trimEnd('/') + "/" + path.trimStart('/')

    private suspend fun getText(path: String): String =
        NetworkClient.client.get(url(path)).bodyAsText()

    suspend fun getResourcesVersions(): ResourcesVersions =
        JsonHelper.json.decodeFromString(getText("inventory/versions/resources_versions.json"))

    suspend fun getAvailableRecitations(): String =
        NetworkClient.client.get(url("inventory/recitations/available_recitations_info_v2.json")).bodyAsText()

    /**
     * Translation reciters come from **this project's own inventory**, not the upstream one:
     * the Azerbaijani entry (`tts_az_v1`) is generated by `tools/tts` and published here, so it
     * can be re-pointed at a new release tag without shipping an app update. `ghraw://` resolves
     * against whichever mirror the user picked, exactly like the timing files do.
     */
    suspend fun getAvailableRecitationTranslations(): String =
        NetworkClient.client.get(
            resolveInventoryUrl(ApiConfig.OWN_TRANSLATION_RECITATIONS_URL)
        ).bodyAsText()

    suspend fun getAvailableWbwInfo(): AvailableWbwInfoModel =
        JsonHelper.json.decodeFromString(getText("inventory/wbw/available_wbw_info_v2.json"))

    /** Streaming translation download; [path] is relative to [baseUrl]. */
    suspend fun <T> getTranslation(path: String, block: suspend (HttpDownloadScope) -> T): T =
        downloadStream(url(path), block)
}
