package com.cafarovceyxun.anamuslim.db.searchindex

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

const val SEARCH_INDEX_DB_VERSION = 2

@Database(
    entities = [
        TranslationSearchContentEntity::class,
        TranslationSearchFtsEntity::class,
        TranslationIndexMetaEntity::class,
    ],
    version = SEARCH_INDEX_DB_VERSION,
    exportSchema = false,
)
@ConstructedBy(SearchIndexDatabaseConstructor::class)
abstract class SearchIndexDatabase : RoomDatabase() {
    abstract fun searchIndexDao(): SearchIndexDao
}

// The `actual` is generated by the Room compiler (KSP) for each target.
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpectedDeclaration")
expect object SearchIndexDatabaseConstructor : RoomDatabaseConstructor<SearchIndexDatabase> {
    override fun initialize(): SearchIndexDatabase
}
