# Mərhələ 2 maketi üçün məzmun: çıxarışlar (hər biri hədisin text_az-ının hərfi parçası olmalıdır — build yoxlayır),
# zikrlər (ərəbcə xam text_ar-dan, transkript text_az-dan, tərcümə kitabın qeydindən) və əzan cədvəli.

# (açar) -> (cild, №, mətn). № 1 iki yerdə var: İman kitabı c1im2.
EX = {
    'niyyah': ('c1', 1, 'Əməllər yalnız niyyətlərə görədir'),
    'redo': ('c1', 205, 'Geri dön və (yenidən) namaz qıl, (çünki,) həqiqətən də, sən (hələ) namaz qılmadın'),
    'teach': ('c1', 205, 'qibləyə yönəlib təkbir et, sonra da Qurandan səninlə (əzbərində) olandan sənə müyəssər (asan) olanı oxu'),
    'takbir': ('c1', 205, 'qibləyə yönəlib təkbir et'),
    'hands_up': ('c1', 329, 'namaza başlayarkən iki əlini çiyinləri səviyyəsində qaldırardı'),
    'hands_ruku': ('c1', 207, 'rüku edəndə əllərini qaldırdı'),
    'hands_rise': ('c1', 329, 'Rükudan başını qaldırdıqda da həmçinin o ikisini qaldırardı'),
    'hands_not': ('c1', 329, 'O bunu səcdələrdə etmirdi'),
    'right_left': ('c1', 330, 'kişi (namaz qılan insan) namazda sağ əlini sol biləyinin üstünə qoysun'),
    'silence': ('c1', 331, 'təkbir ilə qiraət arasında sükut edərdi'),
    'fatiha': ('c1', 334, 'Onun (namazın) içində Kitabın Fatihəsini oxumayanın namazı yoxdur'),
    'opening': ('c1', 335, 'onlar (namazlarını) "Əl-həmdu lilləhi rabbil-aaləmiin" ilə açardılar'),
    'first_two': ('c1', 336, 'Zöhr namazının ilk iki rükətində Fatihə surəsini və iki (başqa) surə oxuyurdu'),
    'last_two': ('c1', 336, 'Digər iki rükətdə (təkcə) Kitabın Fatihəsini oxuyurdu'),
    'silent': ('c1', 339, 'Saqqalının tərpənməsi ilə'),
    'maghrib_heard': ('c1', 341, 'axırıncı dəfə Məğrib namazında oxuduğunu eşitdiyim surədir'),
    'fajr_heard': ('c1', 343, 'Fəcrdə (Fəcr namazında) "Van-nəxlə bəsiqatin"(Qaf surəsi) oxuyurdu'),
    'ruku_calm': ('c1', 205, 'sonra rüku et, ta o vaxtadək ki, rükuda i\'tidal üzrə olasan'),
    'ruku_knees': ('c1', 358, 'rükuya gedəndə əllərini yaxşıca dizlərinin üzərinə qoydu və belini dümdüz saxladı'),
    'ruku_interlock': ('c1', 345, 'Şübhəsiz ki, (əvvəllər) biz də belə edərdik, ancaq bu bizə nəhy edildi'),
    'rise_calm': ('c1', 207, 'Sonra ayaq üstə o qədər qaldı ki, bütün sümükləri yerinə otursun'),
    'rise_long': ('c1', 380, 'qiyamda (o qədər) durardı ki, biz qiyamın uzunluğundan (öz-özümüzə belə) deyərdik'),
    'seven': ('c1', 349, 'Yeddi sümük üzərinə səcdə etməklə əmr olundum'),
    'seven_list': ('c1', 349, 'əllər, dizlər, barmaq ucları və alın üzərinə'),
    'nose': ('c1', 349, 'əlini alnına qoydu, sonra onu burnunun ucuna çatanadək apardı'),
    'sit_left': ('c1', 352, 'O, (namazda) oturanda sol budunun üstündə rahatlıqla oturardı'),
    'all_prayer': ('c1', 205, 'sonra isə (bütün) bunları namazının hamısında et!'),
    'after_death': ('c1', 360, 'nə zaman ki, O, vəfat etdi, biz (belə) dedik: "Əs-Sələəmu alən-Nəbiyyi"'),
    'elbows_up': ('c1', 353, 'Səcdə etdiyin zaman əlini (yerə) qoy və dirsəklərini qaldır'),
    'not_dog': ('c1', 350, 'sizdən heç kim itin (dirsəkləri və sinəsi ilə yerə) sərilməsi kimi (səcdədə) dirsəklərini (yerə) söykəməsin'),
    'toes_qibla': ('c1', 358, 'ayaq barmaqlarının uclarını isə qibləyə tərəf yönəltdi'),
    'between_long': ('c1', 380, 'iki səcdə arasında (o qədər) oturardı ki, hətta biz (öz-özümüzə belə) deyərdik'),
    'takbir_each': ('c1', 328, 'başını (səcdədən) qaldıranda təkbir etdi, iki səcdədən qalxdıqda da təkbir etdi'),
    'rest_sit': ('c1', 354, 'birinci rükətdə axırıncı (ikinci) səcdədən başını qaldırdıqda (bir qədər) oturdu, sonra (ikinci rükətə) qalxdı'),
    'sit_mid': ('c1', 358, 'İkinci rükətdə (təşəhhüdü oxumaq üçün) oturanda sol ayağının üstündə oturdu və sağ ayağını dik tutdu'),
    'sit_last': ('c1', 358, 'Axırıncı rükətdə (təşəhhüdü oxumaq üçün) oturanda isə sol ayağını (sağ tərəfə) çəkdi (sağ ayağının altına keçirdi), sağ ayağını dik vəziyyətdə tutdu və (sol) ombasının üstündə oturdu'),
    'finger': ('c1', 357, 'işarət (şəhadət) barmağı ilə işarə edər, baş barmağını orta barmağının üstünə qoyar'),
    'gaze': ('c1', 356, 'baxışları ilə ona (barmağına) və yaxud ona tərəf baxdı'),
    'finger_qibla': ('c1', 356, 'baş barmağından sonrakı barmağı ilə qibləyə tərəf işarə edib'),
    'choose_dua': ('c1', 359, 'Sonra (özü üçün xoşladığı duanı) seçsin'),
    'four_refuge': ('c1', 361, 'Sizdən biriniz təşəhhüdü bitirdikdən sonra dörd şeydən Allaha sığınsın'),
    'salam_turn': ('c1', 364, 'yanağının bəyazlığı görünənə kimi (dönərək) sağ tərəfinə salam verirdi'),
    # Namazdan sonra
    'after_takbir': ('c1', 366, 'Biz Rəsulullah sallallahu aleyhi və səlləmin namazının bitdiyini təkbirdən başqa bir şeylə bilməzdik'),
    'after_left': ('c1', 365, 'Mən Rəsulullah sallallahu aleyhi və səlləmin (namazdan) çıxıb getməsinin ən çoxunu (qalxıb) sol tərəfdən getdiyini görmüşəm'),
    'after_33': ('c1', 369, 'Hər bir namazın arxasında otuz üç dəfə təsbih edirsən, otuz üç dəfə Ona (Allah Təalaya) həmd edirsən, Onu otuz üç dəfə təkbir edirsən'),
    # Vaxtlar
    't_between': ('c1', 255, '(Fərz namazlar üçün təyin edilən) vaxt(lar) bu ikisinin arasındadır'),
    't_ontime': ('c1', 248, 'Sonra vaxtında qılınan namazdır'),
    't_forgot': ('c1', 250, 'Kim bir namazı unutsa, onu xatırladığı zaman (dərhal) qılsın'),
    't_cool': ('c1', 257, '(odur ki, Zöhr) namazı(nı) sərin vaxta ertələyin!'),
    't_isha': ('c1', 277, 'Əgər ümmətimə ağır olacağından qorxmasaydım, əsla şübhə yoxdur ki, onlara (İşa namazını) bu vaxt qıldırardım'),
    't_rakah': ('c1', 262, 'Kim namazın bir rükətinə çatarsa, artıq (o) namaza çatmışdır'),
    't_after': ('c1', 285, 'Sübhdən (Sübh namazından) sonra Günəş yüksələnədək namaz yoxdur və Əsrdən (Əsr namazından) sonra Günəş itənədək (batanadək) namaz yoxdur'),
    't_noon': ('c1', 289, 'Günəş tam ortada ikən'),
    't_sun': ('c1', 287, 'Namazınızı nə Günəş doğarkən, nə də batarkən qılmağa çalışmayın!'),
    't_women_fajr': ('c1', 279, 'örtüklərinə bürünərək Sübh namazını qılar, sonra da (evlərinə) qayıdardılar'),
    'r_fajr': ('c1', 397, 'Sübh namazını dörd (rükət) qılırsan?!'),
    'r_zuhr': ('c1', 472, 'Mədinədə Zöhr namazını dörd rükət qıldım'),
    'r_four': ('c1', 467, 'muqim (müsəlmanın yaşadığı, iqamət etdiyi yerdə olan kimsə) üçün (Zöhr, Əsr və İşa namazları) dörd (rükət) edildi'),
    'r_maghrib': ('c2', 872, 'O, Məğribi üç rükət'),
    # Qiblə
    'q_ayah': ('c1', 291, '(Odur ki,) üzünü Məscidul-Harama (Kə\'bəyə) tərəf çevir!'),
    'q_turned': ('c1', 292, 'Kə\'bəyə tərəf döndülər'),
    'q_fard': ('c1', 299, 'Fərz namazı qılmaq istəyəndə (isə, miniyindən) enər və qibləyə yönələrdi'),
    'q_mount': ('c1', 293, 'səfərdə miniyinin üstündə (miniyi) hara yönəlsə (ora doğru) namaz qılardı'),
    # Əzan
    'a_pairs': ('c1', 307, 'Bilala əzanı iki-iki, iqaməni isə tək-tək etmək əmr olundu'),
    'a_repeat': ('c1', 308, 'Nidanı eşitdiyiniz zaman müəzzinin dediklərinin mislini (siz də) deyin (təkrar edin)!'),
    'a_loud': ('c1', 304, 'nida (əzan) ilə səsini yüksəlt (əzanı uca səslə oxu)'),
    'a_bilal': ('c1', 302, 'Ey Bilal, qalx və (insanları) namaza çağır (azan oxu)!'),
    'a_two_fajr': ('c1', 309, 'İbn ummi Məktum əzan verənədək yeyin, için'),
    'a_rain': ('c1', 311, 'Diqqət edin! Namazı olduğunuz yerdə qılın!'),
    'a_leave': ('c1', 314, 'artıq o, Əbul-Qasim sallallahu aleyhi və səlləmə asi olmuşdur'),
    # Bilmək lazımdır
    'k_sky': ('c1', 192, 'Bəzi qövmlərə (insanlara) nə olur ki, namazlarında gözlərini səmaya qaldırırlar?'),
    'k_hips': ('c1', 194, 'Namazda ixtisar nəhy olundu'),
    'k_hips_def': ('c1', 194, 'O (ixtisar), namaz qılarkən əllərini yana (böyrünə) qoymaqdır'),
    'k_look': ('c1', 196, 'şeytanın (namaz qılan) qulun namazından oğurladığı(bir pay)dır'),
    'k_talk': ('c1', 203, 'bu namazda insanların kəlamından heç bir şey olmaz'),
    'k_spit': ('c1', 239, 'əsla önünə və sağ tərəfinə tüpürməsin'),
    'k_food': ('c1', 189, 'yemək hazır olduğu və iki xəbis (kiçik və böyük bayır) onu sıxışdırdığı zaman (əsla) namaz qılmasın'),
    'k_sleepy': ('c1', 201, 'yuxu ondan gedənə (yuxusunu alana) qədər yatsın'),
    'k_child': ('c1', 197, 'səcdə edəndə onu yerə qoyar, ayağa qalxanda isə (yenidən qucağına) götürərdi'),
    'k_shoulders': ('c1', 244, 'Sizdən biriniz əsla çiyinlərində bir şey olmadığı halda, bir paltarda namaz qılmasın!'),
    'k_pebbles': ('c1', 198, 'bir dəfə et və ya tərk et (heç etmə)'),
    'k_enter': ('c1', 240, 'oturmazdan əvvəl iki rükət namaz qılsın!'),
    'k_tasbih': ('c1', 200, 'Kimə namazında bir şey üz verərsə, (Allahı) təsbih etsin'),
    'k_clap': ('c1', 200, 'Əl çırpmaq (isə) yalnız qadınlara məxsusdur'),
    'k_mosque_w': ('c1', 231, 'Allahın qullarını (1) Allahın məscidlərindən əngəlləməyin'),
    'k_pass': ('c1', 316, 'heç kimi qabağından keçməyə qoymasın'),
    'k_sutra': ('c1', 325, 'Yəhərin arxalığı kimidir'),
    'k_pass_sin': ('c1', 315, 'onun (namaz qılanın) önündən keçməkdən onun üçün daha xeyirli olardı'),
    'k_light': ('c1', 206, 'namazı xəfif edir və (lakin) rüku və səcdələri tamamlayır'),
}

# Zikrlər. ar: kitabın xam ərəb mətnindən (hərəkəli); tr: text_az-dakı oxunuş; mean: kitabın qeydi və ya mətndaxili izahı.
ZK = {
    'takbir': {'ar': 'اللَّهُ أَكْبَرُ', 'tr': 'Allahu Əkbər', 'mean': 'Allah ən böyükdür', 'ref': ('c1', 327), 'meanSrc': 'təsdiqlənmiş əzan tərcüməsi'},
    'istiftah': {'ar': 'اللَّهُمَّ بَاعِدْ بَيْنِي وَبَيْنَ خَطَايَايَ كَمَا بَاعَدْتَ بَيْنَ الْمَشْرِقِ وَالْمَغْرِبِ، اللَّهُمَّ نَقِّنِي مِنْ خَطَايَايَ كَالثَّوْبِ الأَبْيَضِ مِنَ الدَّنَسِ، اللَّهُمَّ اغْسِلْنِي مِنْ خَطَايَايَ بِالْمَاءِ وَالْبَرَدِ وَالثَّلْجِ',
                 'tr': 'Allahummə! Bəəid beynii va beynə xataayəəyə, kəməə bəadtə beynəl-məşriqi val-məğribi! Allahummə! Nəqqinii min xataayəəyə, kəssəvbil-əbyadi minəd-dənəsi! Allahumməğsilnii min xataayəyə bil-məəi val-bəradi vas-səlci!',
                 'mean': 'Allahummə (Ey Allahım)! Məşriq ilə məğribin arasını (bir-birindən) uzaqlaşdırdığın kimi, mənimlə xətalarımın (günahlarımın) arasını (bir-birimizdən) uzaqlaşdır! Allahummə! Bəyaz paltar kirdən təmizləndiyi kimi, məni də (o şəkildə) günahlarımdan (təmizlə və) saflaşdır! Allahummə! Məni günahlarımdan su, dolu və buz ilə yu (təmizlə)!',
                 'ref': ('c1', 331), 'meanSrc': 'hədisin qeydi'},
    'ruku1': {'ar': 'سُبْحَانَكَ اللَّهُمَّ رَبَّنَا وَبِحَمْدِكَ، اللَّهُمَّ اغْفِرْ لِي', 'tr': 'Subhənəkəllahummə, Rabbənə va bihəmdikə, Allahumməğfir lii',
              'mean': 'Allahummə, Sən pak və nöqsansızsan! Rəbbimiz, Sənə həmd olsun! Allahummə, məni bağışla!', 'ref': ('c1', 346), 'meanSrc': 'hədisin qeydi', 'where': 'rükuda və səcdədə'},
    'ruku2': {'ar': 'سُبُّوحٌ قُدُّوسٌ رَبُّ الْمَلاَئِكَةِ وَالرُّوحِ', 'tr': 'Subbuhun, Quddusun, Rabbul-mələəikəti var-ruuhi',
              'mean': '(Mənim Rəbbim) Subbuhdur (bütün qüsur və nöqsanlardan münəzzəhdir), Quddusdur (üstünlükləri, ucalıqları ilə öyülən, təriflənəndir), mələklərin və Ruhun Rəbbidir!', 'ref': ('c1', 347), 'meanSrc': 'hədisin qeydi', 'where': 'rükuda və səcdədə'},
    'rise': {'ar': 'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا وَلَكَ الْحَمْدُ', 'tr': 'Səmiallahu limən həmidəhu, Rabbənə va ləkəl-həmdu',
             'mean': 'Allah, Ona həmd edən kimsəni eşitdi. Rəbbimiz, Sənədir həmd!', 'ref': ('c1', 329), 'meanSrc': '№ 327-nin rəvayətindəki izah'},
    'tashahhud': {'ar': 'التَّحِيَّاتُ لِلَّهِ، وَالصَّلَوَاتُ لِلَّهِ وَالطَّيِّبَاتُ. السَّلاَمُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ. السَّلاَمُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ. أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
                  'tr': 'Ət-təhiyyəətu lilləhi vas-salavaatu lilləhi vat-tayyibəətu. Əs-Sələəmu aleykə əyyuhən-Nəbiyyu va rahmətullahi va bərakəətuhu. Əs-Sələəmu aleynəə va aləə ibəədilləəhis-saalihiinə. Əşhədu ən ləə iləəhə illəllahu va əşhədu ənnə Muhəmmədən abduhu va rasuuluhu',
                  'mean': '(Bütün) salamlamalar, dualar və xoş, gözəl, pak olan şeylər Allah üçündür. Sənə Allahın rəhməti, Onun bərəkəti və (Allahın) salam(ı) olsun ey Nəbi! Bizə və Allahın saleh qullarına salam olsun. Mən şahidlik edirəm ki, Allahdan başqa ilah yoxdur və mən şahidlik edirəm ki, Muhəmməd Onun qulu və Rəsuludur.',
                  'ref': ('c1', 359), 'meanSrc': 'hədisin qeydi'},
    'refuge': {'ar': 'اللهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، وَأَعُوذُ بِكَ مِنْ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ، وَأَعُوذُ بِكَ مِنْ فِتْنَةِ الْمَحْيَا وَفِتْنَةِ الْمَمَاتِ، اللهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْمَأْثَمِ وَالْمَغْرَمِ',
               'tr': 'Allahummə innii əuuzu bikə min azəəbil-qabri, va əuuzu bikə min fitnətil-məsihid-dəccəəli. Va əuuzu bikə min fitnətil-məhyəə va fitnətil-məməəti. Allahummə innii əuuzu bikə minəl-mə\'səmi val-məğrami',
               'mean': 'Allahummə! Həqiqətən də, mən qəbr əzabından Sənə sığınıram! Məsih Dəccalın fitnəsindən də Sənə sığınıram! Həyatın fitnəsindən və ölümün fitnəsindən də Sənə sığınıram! Allahummə! Şübhəsiz ki, mən günahdan və cərimədən (borcdan) (və yaxud günaha və borca aparan şeydən) Sənə sığınıram!',
               'ref': ('c1', 362), 'meanSrc': 'hədisin qeydi'},
    'salam_after': {'ar': 'اللَّهُمَّ أَنْتَ السَّلاَمُ وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَالإِكْرَامِ', 'tr': 'Allahummə əntəs-sələəmu va minkəs-sələəmu, təbəəraktə yəə zəl-cələli val-ikrami',
                    'mean': 'Allahummə! Sənsən əs-Salam! Salamatlıq da məhz Səndəndir! Ey cəlal və ikram sahibi! Sənin şanın nə ucadır!', 'ref': ('c1', 367), 'meanSrc': 'hədisin qeydi'},
    # Salamın sözləri istifadəçidəndir (2026-10-04); kitabda yoxdur, ona görə build yoxlamır. Tərcümə təklifdir.
    'salam': {'ar': 'السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ', 'tr': 'Əs-sələmu aleykum va rahmətullah', 'mean': 'Sizə Allahın salamı və rəhməti olsun',
              'ref': ('c1', 364), 'meanSrc': 'təklif, təsdiq gözləyir · mətni siz verdiniz', 'user': True},
    'tahlil': {'ar': 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ', 'tr': 'Ləə iləəhə illəllahu vahdəhu ləə şəriikə ləhu, ləhul-mulku va ləhul-həmdu, va huva aləə kulli şey\'in qadiirun',
               'mean': 'Allahdan başqa ilah yoxdur, O təkdir, Onun heç bir şəriki yoxdur. Yalnız Onundur mülk və həmd də yalnız Ona məxsusdur və O, hər şeyə qadirdir.', 'ref': ('c1', 369), 'meanSrc': 'hədisin qeydi'},
}

# Təsbih sayğacı (№ 369): sözlər babın adındandır.
COUNTER = [
    {'ar': 'سُبْحَانَ اللَّهِ', 'tr': 'Subhənallah', 'n': 33},
    {'ar': 'الْحَمْدُ لِلَّهِ', 'tr': 'Əlhəmdulilləh', 'n': 33},
    {'ar': 'اللَّهُ أَكْبَرُ', 'tr': 'Allahu əkbər', 'n': 33},
]

# Əzan cədvəli — istifadəçinin verdiyi (Mərhələ 1 maketindəki ADHAN massivi, hərfi).
ADHAN = [
    {"tr": "Allahu Əkbər", "ar": "اللَّهُ أَكْبَرُ", "arSrc": None, "mean": "Allah ən böyükdür", "meanSrc": None, "adhan": 2, "iqama": 1},
    {"tr": "Əşhədu əllə iləhə illəllah", "ar": "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ", "arSrc": "226", "mean": "Şahidlik edirəm ki, Allahdan başqa ilah yoxdur", "meanSrc": "359", "adhan": 2, "iqama": 1},
    {"tr": "Əşhədu ənnə Muhəmmədən rasulullah", "ar": "أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ", "arSrc": "226", "mean": "Şahidlik edirəm ki, Muhəmməd Allahın Rəsuludur", "meanSrc": "359", "adhan": 2, "iqama": 1},
    {"tr": "Həyyə aləs-saləh", "ar": "حَيَّ عَلَى الصَّلَاةِ", "arSrc": "226", "mean": "Namaza gəlin", "meanSrc": None, "adhan": 2, "iqama": 1},
    {"tr": "Həyyə aləl-fələh", "ar": "حَيَّ عَلَى الْفَلاَحِ", "arSrc": "306", "mean": "Qurtuluşa gəlin", "meanSrc": None, "adhan": 2, "iqama": 1},
    {"tr": "Qad-qamətis - saləh", "ar": "قَدْ قَامَتِ الصَّلَاةُ", "arSrc": None, "mean": "Namaz başladı", "meanSrc": None, "adhan": 0, "iqama": 2, "trSrc": "307"},
    {"tr": "Allahu Əkbər", "ar": "اللَّهُ أَكْبَرُ", "arSrc": None, "mean": "Allah ən böyükdür", "meanSrc": None, "adhan": 2, "iqama": 1},
    {"tr": "Lə iləhə illəllah", "ar": "لَا إِلَهَ إِلَّا اللَّهُ", "arSrc": "369", "mean": "Allahdan başqa ilah yoxdur", "meanSrc": "369", "adhan": 2, "iqama": 1},
]

# Hədis vərəqində göstəriləcək əlavə istinadlar (çıxarışı olmayanlar).
EXTRA_REFS = [('c1', n) for n in (226, 306, 359, 360, 327, 332, 333, 337, 255, 252, 254, 281, 282, 283, 286, 288, 290, 294, 295, 296, 301,
                                  303, 310, 312, 313, 191, 193, 195, 204, 235, 236, 243, 245, 246, 324, 362, 363, 367, 368, 370, 209, 380)]
