# (slug, ad, yeni?) — sort sırası
CATS = [
 ('namaz-2','Namaz',False),
 ('namaz','Ayaqyoluna girərkən edilən zikr',False),
 ('ehzab-gunu-nebi-sallallahu-aleyhi-ve-sellem-dusmene-qarsi-etdiyi-dua','Əhzab günü Nəbi sallallahu aleyhi və səlləmin düşmənə qarşı etdiyi dua',False),
 ('gazve-hecc-ve-ya-umreden-qayidarken-yuksek-tepeye-cixanda-3-defe-tekbir-edib-edi','Ğazvə, həcc və ya ümrədən qayıdarkən',False),
 ('seher-ve-axsam-zikirleri','Səhər və axşam zikirləri',False),
 ('gun-erzinde-mueyyen-sayda-eilen-zikrler','Gün ərzində müəyyən sayda edilən zikrlər',False),
 ('kelamin-allaha-en-sevimli-olani-dorddur','Kəlamın Allaha ən sevimli olanı dörddür',False),
 ('yatmazdan-once-ve-oyanarken-edilen-zikirler','Yatmazdan öncə və oyanarkən edilən zikirlər',False),
 ('nebinin-dualari','Nəbi sallallahu aleyhi və səlləmin etdiyi dualar',True),
 ('istiaze-dualari','İstiazə (Allaha sığınma) duaları',True),
 ('nebiye-salavat','Nəbiyə salavat',True),
 ('sefer-dualari','Səfər duaları',True),
 ('sixinti-ve-musibet-zamani','Sıxıntı və müsibət zamanı',True),
 ('xestelik-ve-ruqye','Xəstəlik və ruqyə',True),
 ('yagis-kulek-ve-bulud','Yağış və külək',True),
 ('yemek-ve-qonaqliq','Yemək və qonaqlıq',True),
 ('aile-heyati','Ailə həyatı',True),
 ('hecc-ve-umre','Həcc və Ümrə',True),
 ('muxtelif-hallarda','Müxtəlif hallarda zikr',True),
 ('dusmen-qarsisinda','Düşmən qarşısında',True),
 ('sexsler-qovmler-ve-yerler-ucun','Şəxslər, qövmlər və yerlər üçün dualar',True),
 ('xususi-hallarda-nebinin-sozleri','Xüsusi hallarda Nəbinin Allaha xitabı',True),
 ('olum-ve-son-anlar','Ölüm və son anlar',True),
]
SUBS = {  # yeni alt başlıqlar (namaz-2)
 'rukuda-deyilen-zikr':('Rukuda deyilən zikr',False),
 'rukudan-basini-qaldiranda-ne-deyilir':('Rükudan başını qaldıranda nə deyilir!',False),
 'secdede-edilen-zikr':('Səcdədə edilən zikr',False),
 'tesehhudde-oxunan-dua':('Təşəhhüddə oxunan dua',False),
 'namazda-edilen-dua':('Namazda (salamdan əvvəl) edilən dua',True),
 'namazda-bir-sey-uz-verende':('Namazda bir şey üz verəndə',True),
 'gece-namazinda-dua':('Gecə namazında dua',True),
 'qunut':('Qunut',True),
 'yatarken-edilen-zikr':('Yatarkən edilən zikr',False),
}
