# İkinci dalğa (2026-10-06, gec): istifadəçinin baxış səhifəsindən geri qaytardığı bəndlər + eyni sözlü ikinci rəvayətlər.
# Nəbinin (s.a.s.) sözü olmayanlarda kimin dediyi qeyd sətrində hədisin öz mətnindən göstərilir.
EXTRA = [
    # --- Geri qaytarılanlar ---
    dict(cat='namaz-2', sub='rukudan-basini-qaldiranda-ne-deyilir', hid=392, sort=40,
         ar=('اللهم ربنا لك الحمد ملء السماوات', 'منك الجد'),
         tr=('Allahummə, Rabbənə ləkəl-həmdu, mil\'əs-səməəvaati', 'zəl-cəddi minkəl-cəddu'),
         az=('note', 'Allahummə, ey Rəbbimiz! Sənədir həmd!', 'zənginliyi fayda verməz!'),
         note=('text_az', 'Mətar ibn Nəciyə, ibnul-Əş\'əs günlərində Əbu Ubeydə ibn Abdullahı', 'onu sözünü demişdir')),
    dict(cat='hecc-ve-umre', sub=None, hid=1044, sort=60,
         ar=('باسم الله والله اكبر', None),
         tr=('Bismilləhi vallahu Əkbəru', None),
         az=('LIT', ''),
         note=('text_az', 'İbn Ömər harama yaxınlaşdıqda təlbiyə etməyi tərk edər', 'Həcəri istilam edər və (belə) deyərdi')),
    dict(cat='muxtelif-hallarda', sub=None, hid=888, sort=40,
         ar=('اني صائم', None),
         tr=None,
         az=('text_az', 'Əgər kimsə ona qarşı cahillik etsə və ya ona əziyyət versə, (belə) desin:"Həqiqətən də mən orucluyam!', None),
         note=None),
    dict(cat='muxtelif-hallarda', sub=None, hid=2666, sort=50,
         ar=('لا خلابه', None),
         tr=None,
         az=('text_az', 'Kiminlə alış-veriş etsən (ona belə) de:"Aldatmaq yoxdur', None),
         note=None),
    dict(cat='muxtelif-hallarda', sub=None, hid=3085, sort=60,
         ar=('اذا سلم عليك اهل الكتاب', 'وعليكم'),
         tr=None,
         az=('text_az', 'Kitab əhli sizə salam verdikdə (siz də belə) deyin:"Va aleykum (sizə də', None),
         note=None),

    # --- Əvvəlki nəbilərin və ümmətlərin duaları (yeni başlıq) ---
    dict(cat='evvelki-nebi-ve-ummetlerin-dualari', sub=None, hid=1438, sort=10,
         ar=('اللهم بارك لهم في طعامهم وشرابهم', None),
         tr=None,
         az=('text_az', 'O dedi:"Allahummə! Onların yeməklərinə və içməklərinə bərəkət ver!', None),
         note=('text_az', '(Bu,) İbrahimin duası ilə olan bir bərəkətdir', None)),
    dict(cat='evvelki-nebi-ve-ummetlerin-dualari', sub=None, hid=1439, sort=20,
         ar=('اللهم ان كنت تعلم اني امنت بك وبرسولك', 'الكافر'),
         tr=None,
         az=('text_az', 'Allahummə! Əgər Sən bilirsən ki, mən Sənə və Rəsuluna iman etmişəm', '(bu kafirin mənə güc gəlməsinə imkan vermə)'),
         note=('text_az', '(Saranın bu duasından dərhal sonra) o, elə boğuldu ki, hətta ayağını (yerə) vurmağa başladı', None)),
    dict(cat='evvelki-nebi-ve-ummetlerin-dualari', sub=None, hid=3472, sort=30,
         ar=('ضربه قومه فادموه', 'لا يعلمون'),
         tr=None,
         az=('text_az', 'Qövmü onu vurmuş və (üzünü və ya başını yararaq) qanatmışdır', 'həqiqətən də onlar bilmirlər'),
         note=('text_az', 'Nəbi sallallahu aleyhi və səlləmə baxıram, O da nəbilərdən bir nəbi haqqında danışır', None)),
    dict(cat='evvelki-nebi-ve-ummetlerin-dualari', sub=None, hid=3509, sort=40,
         ar=('اللهم ان كنت فعلت ذلك ابتغاء وجهك', 'الصخره'),
         tr=None,
         az=('text_az', 'Allahummə, əgər mən bunu Sənin Üzünü dilədiyimə görə etmişəmsə, bizi bu qaya parçasına görə düşdüyümüz (çətinlik)dən qurtar!', None),
         note=('text_az', 'Həqiqətən də, sizi bu qaya parçasından yalnız (etdiyiniz) saleh əməllərinizlə Allaha dua etməyiniz xilas edə bilər', None)),
    dict(cat='evvelki-nebi-ve-ummetlerin-dualari', sub=None, hid=3513, sort=50,
         ar=('اللهم لا تمته حتى', 'المومسه'),
         tr=None,
         az=('text_az', '(Onda anası belə) dedi:"Allahummə!Ona', 'onu öldürmə!'),
         note=None),
    dict(cat='evvelki-nebi-ve-ummetlerin-dualari', sub=None, hid=3510, sort=60,
         ar=('اللهم اكفنيهم بما شئت', None),
         tr=None,
         az=('text_az', '(gənc) dedi:"Allahummə!Onlara qarşı mənə istədiyin şeylə kifayət et!', None),
         note=None),

    # --- Zikr və duanın fəziləti və ədəbi (yeni başlıq) ---
    dict(cat='zikr-ve-duanin-fezileti', sub=None, hid=3202, sort=10,
         ar=('لا يقعد قوم', 'فيمن عنده'),
         tr=None,
         az=('text_az', 'Oturub Allahı zikr edən elə bir qövm olmasın', 'Öz yanında olanların içində zikr etməsin'),
         note=None),
    dict(cat='zikr-ve-duanin-fezileti', sub=None, hid=3243, sort=20,
         ar=('ينزل ربنا', 'فاغفر له'),
         tr=None,
         az=('text_az', 'Rəbbimiz təbarəkə və təalə, hər gecə, gecənin son üçdə biri qalanda', '(onu) bağışlayım?'),
         note=None),
    dict(cat='zikr-ve-duanin-fezileti', sub=None, hid=3231, sort=30,
         ar=('لا يقل احدكم اذا دعا', 'لا مكره له'),
         tr=None,
         az=('text_az', 'Sizdən biriniz dua etdikdə (belə) deməsin', 'Onu məcbur edən yoxdur'),
         note=None),
    dict(cat='zikr-ve-duanin-fezileti', sub=None, hid=3238, sort=40,
         ar=('رايت رسول الله', 'بياض ابطيه'),
         tr=None,
         az=('text_az', 'Rəsulullah sallallahu aleyhi və səlləmi gördüm, duada əllərini qaldırardı', 'qoltuq altının ağlığı görünürdü'),
         note=None),
    dict(cat='zikr-ve-duanin-fezileti', sub=None, hid=3236, sort=50,
         ar=('كان لا يرفع يديه', 'بياض ابطيه'),
         tr=None,
         az=('text_az', 'Nəbi sallallahu aleyhi və səlləm istisqa', 'yuxarı qaldırardı'),
         note=None),

    # --- Eyni sözlü ikinci rəvayətlər ---
    dict(cat='yatmazdan-once-ve-oyanarken-edilen-zikirler', sub='yatarken-edilen-zikr', hid=3223, sort=40,
         ar=('اللهم باسمك احيا', 'اموت'),
         tr=('Allahummə bismikə əhyəə va bismikə əmuutu', None),
         az=('note', 'Allahummə! Sənin adınla ölürəm və Sənin adınla dirilirəm!', None),
         note=None),
    dict(cat='yatmazdan-once-ve-oyanarken-edilen-zikirler', sub='yatarken-edilen-zikr', hid=3229, sort=50,
         ar=('اللهم اسلمت نفسي اليك', 'ارسلت'),
         tr=('Allahummə, əsləmtu nəfsii ileykə', 'binəbiyyikəlləzii ərsəltə'),
         az=('note', 'Allahummə! Sənə ümid edərək və Səndən qorxaraq nəfsimi Sənə təslim etdim', 'Nəbiyə iman gətirdim!'),
         note=('text_az', 'Əgər (o, bu hal üzərində) ölsə, fitrət üzrə ölmüş olar', None)),
    dict(cat='gazve-hecc-ve-ya-umreden-qayidarken-yuksek-tepeye-cixanda-3-defe-tekbir-edib-edi', sub=None, hid=3217, sort=10,
         ar=('لا اله الا الله وحده لا شريك له', 'حامدون'),
         tr=('Ləə iləəhə illəllahu, vahdəhu ləə şəriikə ləhu, ləhul-mulku', 'lirabbinə həəmiduunə'),
         az=('note', 'Allahdan başqa ilah yoxdur', 'Tək Özü məğlub etdi'),
         note=None),
    dict(cat='nebiye-salavat', sub=None, hid=1341, sort=50,
         ar=('اللهم بارك على محمد', 'حميد مجيد'),
         tr=('Allahummə bəərik aləə Muhəmmədin va aləə əəli Muhəmmədin', 'innəkə həmidun məcidun'),
         az=('LIT', ''),
         note=('text_az', '(Mənə) salət edin və (dua etməkdə) ictihad edin (çox çalışın)!', None)),
    dict(cat='yagis-kulek-ve-bulud', sub=None, hid=3246, sort=15,
         ar=('اللهم صيبا هنيئا', None),
         tr=('Allahummə, sayyibən həniiən', None),
         az=('note', '(Allahummə, (bu yağışı) faydalı, (yaxşı və s.) et!)', None),
         note=None),
]
