# Zikr və Dua kitabı (Muheymin 7, № 2807–2876, hadith.id 3200–3269)
# R(cat, sub, hid, ar, tr, az, note, rep, sort, parts)
#   ar  = (start, end[, marker])            — hədisin text_ar-ından (hərəkəsiz lövbər)
#   tr  = (start, end[, after]) | None      — oxunuş, text_az-dan
#   az  = (field, start, end[, after])      — tərcümə: 'note' və ya 'text_az'
#   note= (field, start, end[, after]) | None — fəzilət/şərh, hədisin öz sözü
ZIKR = [
    # --- Gün ərzində (mövcud başlıq) ---
    dict(cat='gun-erzinde-mueyyen-sayda-eilen-zikrler', sub=None, hid=3212, sort=10,
         ar=('لا حول ولا قوه الا بالله', 'لا حول ولا قوه الا بالله', 'الا ادلك على كلمه'),
         tr=('Ləə həvlə va ləə quvvatə illəə billəhi', None, 'Səni Cənnət xəzinələrindən'),
         az=('note', 'Güc və qüvvət yalnız Allaha məxsusdur', None),
         note=('text_az', 'Səni Cənnət xəzinələrindən bir xəzinə (olan) bir kəliməyə yönəltməyimmi?', None)),

    # --- Yatmazdan öncə (mövcud başlıq, alt başlıq yatarkən) ---
    dict(cat='yatmazdan-once-ve-oyanarken-edilen-zikirler', sub='yatarken-edilen-zikr', hid=3227, sort=10,
         ar=('LIT', 'اللَّهُ أَكْبَرُ'), tr=('LIT', 'Allahu Əkbər'), az=('LIT', ''), rep=34,
         note=('text_az', 'Yatağınıza uzandığınız zaman otuz dörd dəfə təkbir edin', 'Bu, sizin üçün xidmətçidən daha xeyirlidir'),
         parts=[dict(ar=('LIT', 'سُبْحَانَ اللَّهِ'), tr=('LIT', 'SubhənAllah'), az=('LIT', ''), rep=33),
                dict(ar=('LIT', 'الْحَمْدُ لِلَّهِ'), tr=('LIT', 'Əlhəmdulilləh'), az=('LIT', ''), rep=33)]),
    dict(cat='yatmazdan-once-ve-oyanarken-edilen-zikirler', sub='yatarken-edilen-zikr', hid=3228, sort=20,
         ar=('كل ليله جمع كفيه', 'ثلاث مرات'),
         tr=None,
         az=('text_az', 'Nəbi sallallahu aleyhi və səlləm hər gecə yatağına uzananda ovuclarını birləşdirər', 'O, bunu üç dəfə edərdi'),
         note=None),
    dict(cat='yatmazdan-once-ve-oyanarken-edilen-zikirler', sub='yatarken-edilen-zikr', hid=3221, sort=30,
         ar=('من قرا بالايتين', 'كفتاه'),
         tr=None,
         az=('text_az', 'Kim gecə Bəqərə surəsinin sonundakı iki ayəti oxusa', 'o ikisi ona kifayət edər'),
         note=None),

    # --- Səfər (yeni) ---
    dict(cat='sefer-dualari', sub=None, hid=3211, sort=10,
         ar=('اللهم انت الصاحب في السفر', 'في الاهل والمال'),
         tr=('Allahummə əntəs-sahibu fis-səfəri', 'fil-əhli val-məli'),
         az=('note', 'Allahummə!Səfərdə bizə dost', 'Sənə sığınıram!'),
         note=None),
    dict(cat='sefer-dualari', sub=None, hid=3213, sort=20,
         ar=('كنا اذا صعدنا كبرنا', 'سبحنا'),
         tr=None,
         az=('text_az', 'Biz (Rəsulullah sallallahu aleyhi və səlləmin zamanında bir yüksək yerə) çıxanda təkbir edərdik', 'enəndə isə təsbih edərdik'),
         note=None),
    dict(cat='sefer-dualari', sub=None, hid=3212, sort=30,
         ar=('يا ايها الناس اربعوا على انفسكم', 'وتعالى جده', 'وفي روايه'),
         tr=None,
         az=('text_az', 'Ey insanlar! Özünüzə qarşı yumşaq olun', 'nə ucadır Onun əzəməti!'),
         note=None),
    dict(cat='sefer-dualari', sub=None, hid=3269, sort=40,
         ar=('اعوذ بكلمات الله التامات', 'من شر ما خلق'),
         tr=('Əuuzu bikəliməətilləhit-təəməəti min şərri mə xaləqa', None),
         az=('note', 'Yaratdıqlarının şərindən Allahın tam kəlimələrinə sığınıram!', None),
         note=('text_az', 'ordan gedənə qədər ona heç bir şey zərər verməz', None)),

    # --- Sıxıntı (yeni) ---
    dict(cat='sixinti-ve-musibet-zamani', sub=None, hid=3218, sort=10,
         ar=('لا اله الا الله العظيم الحليم', 'رب العرش الكريم}}'),
         tr=('Ləə iləəhə illəllahul-Aziimul-Həliimu', 'Rabbul-arşil-kəriimi}}'),
         az=('note', 'Azim (Əzəmətli) və Həlim', 'yerin Rəbbi və kərim ərşin Rəbbi (olan) Allahdan başqa ilah yoxdur.'),
         note=None),
    dict(cat='sixinti-ve-musibet-zamani', sub=None, hid=3233, sort=20,
         ar=('اللهم احيني', 'اذا كانت الوفاه خيرا لي'),
         tr=('Allahummə! Əhyinii', 'xayran lii"'),
         az=('note', 'Allahummə! Həyat mənim üçün', 'məni öldür!'),
         note=('text_az', 'Ona üz verən zərərə görə sizdən biriniz əsla ölümü təmənna etməsin', None)),

    # --- İstiazə (yeni) ---
    dict(cat='istiaze-dualari', sub=None, hid=3260, sort=10,
         ar=('تعوذوا بالله من جهد البلاء', 'شماته الاعداء'),
         tr=None,
         az=('text_az', 'Bəlanın məşəqqətindən, bədbəxt olmaqdan, pis taledən və düşmənlərin bədxahlığından Allaha sığının', None),
         note=None),
    dict(cat='istiaze-dualari', sub=None, hid=3261, sort=20,
         ar=('عوذوا بالله من عذاب الله', 'المسيح الدجال'),
         tr=None,
         az=('text_az', 'Allahın əzabından Allaha sığının!', 'Məsih Dəccalın fitnəsindən Allaha sığının!'),
         note=None),
    dict(cat='istiaze-dualari', sub=None, hid=3263, sort=30,
         ar=('اللهم اني اعوذ بك من عذاب القبر', 'المسيح الدجال'),
         tr=('Allahummə! İnni əuuzu bikə min azəbil-qabri', 'fitnətil-məsihid-dəccəəli'),
         az=('note', 'Allahummə! Həqiqətən də mən qəbir əzabından', 'Sənə sığınıram!'),
         note=None),
    dict(cat='istiaze-dualari', sub=None, hid=3264, sort=40,
         ar=('اللهم فاني اعوذ بك من فتنه النار', 'والمغرم'),
         tr=('Allahummə! Fəinnii əuuzu bikə min fitnətin-nəəri', 'val-məğrami'),
         az=('note', 'Allahummə! Həqiqətən də mən Od (Cəhənnəm) fitnəsindən', '(və yaxud günaha və borca aparan şeydən) Sənə sığınıram!'),
         note=None),
    dict(cat='istiaze-dualari', sub=None, hid=3265, sort=50,
         ar=('اللهم اني اعوذ بك من العجز', 'المحيا والممات'),
         tr=('Allahummə!İnnii əuuzu bikə minəl-aczi', 'fitnətil-məhyəə val-məməəti'),
         az=('note', 'Allahummə! Həqiqətən də mən acizlikdən', '(də) Sənə sığınıram!'),
         note=None),
    dict(cat='istiaze-dualari', sub=None, hid=3266, sort=60,
         ar=('اعوذ بك من البخل', 'المحيا والممات'),
         tr=('(Allahummə!) Əuuzu bikə minəl-buxli', 'fitnətil-məhyəə val-məməəti'),
         az=('note', 'Allahummə! Simiclikdən', 'Sənə sığınıram!'),
         note=None),
    dict(cat='istiaze-dualari', sub=None, hid=3267, sort=70,
         ar=('اللهم اني اعوذ بك من الكسل', 'من البخل'),
         tr=('Allahummə!İnnii əuuzu bikə minəl-kəsəli', 'minəl-buxli'),
         az=('note', 'Allahummə! Tənbəllikdən', 'Sənə sığınıram!'),
         note=None),
    dict(cat='istiaze-dualari', sub=None, hid=3268, sort=80,
         ar=('اللهم اني اعوذ بك من العجز', 'لا يستجاب لها'),
         tr=('Allahummə!İnnii ə‘uuzu bikə minəl-aczi', 'yustəcəəbu ləhəə'),
         az=('note', 'Allahummə! Həqiqətən də mən acizlikdən', 'Sənə sığınıram!"'),
         note=('text_az', 'Rəsulullah sallallahu aleyhi və səlləm onları bizə öyrədirdi, biz də onları sizə öyrədirik', None)),

    # --- Nəbinin duaları (yeni) ---
    dict(cat='nebinin-dualari', sub=None, hid=3254, sort=10,
         ar=('اللهم اتنا في الدنيا حسنه', 'عذاب النار'),
         tr=('Allahummə! Əətinəə fid-dunyə həsənətən', 'azəbən-nəəri'),
         az=('text_az', 'Allahummə! Bizə həm (bu) dünyada', 'Od əzabından qoru!', None, 2873),
         note=('text_az', 'Nəbi sallallahu aleyhi və səlləm duasında belə deməyi çoxaldardı', None)),
    dict(cat='nebinin-dualari', sub=None, hid=3255, sort=20,
         ar=('اللهم اني اسالك الهدى', 'والغنى'),
         tr=('Allahummə! İnnii əs\'əlukəl-hudəə', 'val-ğinəə'),
         az=('note', 'Allahummə! Həqiqətən də mən Səndən hidayət', 'istəyirəm!'),
         note=None),
    dict(cat='nebinin-dualari', sub=None, hid=3257, sort=30,
         ar=('اللهم لك الحمد ملء السماء', 'من الوسخ'),
         tr=('Allahummə ləkəl-həmdu, mil\'əs-səməəi', 'minəl-vasəxi"'),
         az=('note', 'Allahummə! Sənə aiddir həmd', 'günahlardan təmizlə və saflaşdır!'),
         note=None),
    dict(cat='nebinin-dualari', sub=None, hid=3259, sort=40,
         ar=('اللهم اصلح لي ديني', 'من كل شر'),
         tr=('Allahummə əslih lii diniyəlləzi', 'min kulli şərrin'),
         az=('note', 'Allahummə, işlərimin isməti', 'hər bir şərdən rahatlıq et!'),
         note=None),

    # --- Salavat (yeni) ---
    dict(cat='nebiye-salavat', sub=None, hid=3251, sort=10,
         ar=('اللهم صل على محمد وعلى ال محمد', 'كما باركت على ال ابراهيم انك حميد مجيد'),
         tr=('Allahummə salli aləə Muhəmmədin va alə əəli Muhəmmədin', 'innəkə həmidun məcidun"'),
         az=('note', 'Allahummə! İbrahim ailəsinə salət etdiyin kimi', 'Sən Həmidsən, Məcidsən!"'),
         note=None),
    dict(cat='nebiye-salavat', sub=None, hid=3250, sort=20,
         ar=('اللهم صل على محمد وازواجه', 'حميد مجيد'),
         tr=('Allahummə salli aləə Muhəmmədin va əzvaacihi', 'innəkə həmidun məcidun'),
         az=('note', 'Allahummə! İbrahim ailəsinə salət etdiyin kimi', 'Sən Həmidsən, Məcidsən!"'),
         note=None),
    dict(cat='nebiye-salavat', sub=None, hid=3252, sort=30,
         ar=('اللهم صل على محمد عبدك ورسولك', 'كما باركت على ابراهيم'),
         tr=('Allahummə!Salli aləə Muhəmmədin, abdikə va rasulikə', 'aləə əəli İbrahimə"'),
         az=('note', 'Allahummə! İbrahim ailəsinə salət etdiyin kimi, qulun', 'Muhəmmədə də bərəkət ver!"'),
         note=None),
    dict(cat='nebiye-salavat', sub=None, hid=3253, sort=40,
         ar=('اللهم صل على محمد وعلى ال محمد', 'حميد مجيد'),
         tr=('Allahummə salli aləə Muhəmmədin va aləə əəli Muhəmmədin, kəməə salleytə aləə İbrahimə', 'innəkə Həmidun, Məcidun"'),
         az=('note', 'Allahummə! İbrahimə salət etdiyin kimi', 'Sən Həmidsən, Məcidsən!"'),
         note=None),

    # --- Yağış, külək (yeni) ---
    dict(cat='yagis-kulek-ve-bulud', sub=None, hid=3246, sort=10,
         ar=('صيبا نافعا', None),
         tr=('(Allahummə) sayyibən nəəfiən', None),
         az=('note', '(Allahummə, bu yağışı) faydalı yağış et!', None),
         note=None),

    # --- Yemək və qonaqlıq (yeni) ---
    dict(cat='yemek-ve-qonaqliq', sub=None, hid=3248, sort=10,
         ar=('اللهم بارك لهم فيما رزقتهم', 'وارحمهم'),
         tr=('Allahummə bəərik ləhum fiiməə razəqtəhum', 'varhəmhum'),
         az=('note', 'Allahummə! Onlara verdiyin ruzidə', 'onlara rəhm et!'),
         note=None),

    # --- Ailə (yeni) ---
    dict(cat='aile-heyati', sub=None, hid=3249, sort=10,
         ar=('بسم الله اللهم جنبنا الشيطان', 'ما رزقتنا'),
         tr=('Bismilləhi, Allahummə!Cənnibnəş-şeytaanə', 'məə razəqtənəə"'),
         az=('note', 'Allahummə! Bizi şeytandan uzaqlaşdır', 'bizi ruziləndirdiyindən uzaqlaşdır'),
         note=('text_az', 'və onlar arasında uşaq təqdir olunsa, o, ona zərər verməz', None)),

    # --- Xüsusi hallar (yeni) ---
    dict(cat='muxtelif-hallarda', sub=None, hid=3245, sort=10,
         ar=('اذا سمعتم صياح الديكه', 'فانه راى شيطانا'),
         tr=None,
         az=('text_az', 'Xoruzun banlamasını eşitdikdə', 'həqiqətən də o, şeytan görmüşdür'),
         note=None),
    dict(cat='muxtelif-hallarda', sub=None, hid=3220, sort=20,
         ar=('اغلق بابك', 'واذكر اسم الله', None, 'واوك سقاءك'),
         tr=None,
         az=('text_az', 'Qapını bağla və Allahın adını onun üzərinə zikr et', 'bağla və Allahın adını zikr et'),
         note=None),

    # --- Ölüm və son anlar (yeni) — yox, bu kitabda yalnız 3233 var (Sıxıntıda)

    # --- Xüsusi hal: Xalid ---
    dict(cat='xususi-hallarda-nebinin-sozleri', sub=None, hid=3240, sort=10,
         ar=('اللهم اني ابرا اليك مما صنع خالد', None),
         tr=('Allahummə! İnnii əbrau ileykə mimməə sanə\'a Xalidun!', None),
         az=('note', 'Allahummə, həqiqətən də, mən Xalidin etdiyindən Sənə təbərri edirəm!', None),
         note=None),
]
