# Zikr kitabından kənar hədislər. Forma data_zikr.py ilə eynidir.
# ar/az/tr lövbərlərinə əlavə açarlar: sa (başlanğıcı bu işarədən sonra axtar), ea (sonu bu işarədən sonra axtar)
NS = 'namaz-2'
REST = [
    # ---------------- Namaz ----------------
    dict(cat=NS, sub='rukuda-deyilen-zikr', hid=518, sort=10,
         ar=('اللهم لك ركعت', 'رب العالمين'),
         tr=('Allahummə ləkə rakə\'tu', 'lilləhi rabbil-aləmin'),
         az=('note', 'Allahummə! Sənə rüku etdim', 'Allahdan qorxdu!'), note=None),
    dict(cat=NS, sub='rukuda-deyilen-zikr', hid=531, sort=20,
         ar=('سبحانك اللهم ربنا وبحمدك', 'اللهم اغفر لي'),
         tr=('Subhənəkəllahummə, Rabbənə va bihəmdikə, Allahumməğfir lii', None),
         az=('note', 'Allahummə, Sən pak və nöqsansızsan!', 'Allahummə, məni bağışla!'),
         note=('text_az', 'Rəsulullah sallallahu aleyhi və səlləm rüku və səcdələrində belə deməyi çox edərdi', None)),
    dict(cat=NS, sub='rukudan-basini-qaldiranda-ne-deyilir', hid=514, sort=10,
         ar=('سمع الله لمن حمده', 'ربنا ولك الحمد'),
         tr=('Səmiallahu limən həmidəhu, Rabbənə va ləkəl-həmdu', None),
         az=('LIT', ''), note=None),
    dict(cat=NS, sub='rukudan-basini-qaldiranda-ne-deyilir', hid=3256, sort=20,
         ar=('سمع الله لمن حمده', 'من شيء بعد', 'اذا رفع راسه من الركوع'),
         tr=('Səmiə\'l-lahu limən həmidəhu', 'min şey\'in bə\'du', 'başını rükudan qaldıranda'),
         az=('note', 'Allahummə, ey Rəbbimiz! Sənə aiddir həmd', 'dolusu (Sənə həmd olsun)!'),
         note=('text_az', 'Rəsulullah sallallahu aleyhi və səlləm başını rükudan qaldıranda (belə) deyirdi', None)),
    dict(cat=NS, sub='rukudan-basini-qaldiranda-ne-deyilir', hid=3258, sort=25,
         ar=('سمع الله لمن حمده', 'من شيء بعد', 'رفع راسه'),
         tr=('Səmia\'llahu limən həmidəhu, mil\'əs-səməəvaati', 'min şey\'in bə\'du', 'Başını (rükudan) qaldırdıqda'),
         az=('note', 'Allah Ona həmd edəni eşitdi.', 'dolusu (Sənə həmd olsun)'), note=None),
    dict(cat=NS, sub='rukudan-basini-qaldiranda-ne-deyilir', hid=602, sort=30,
         ar=('اللهم ربنا لك الحمد', None),
         tr=('Allahummə, Rabbənə ləkəl-həmdu', None),
         az=('LIT', ''),
         note=('text_az', 'İmam: "Səmallahu limən-həmidəhu"-dedikdə siz', 'onun keçmiş günahları bağışlanar')),
    dict(cat=NS, sub='secdede-edilen-zikr', hid=753, sort=10,
         ar=('اللهم اعوذ برضاك من سخطك', 'كما اثنيت على نفسك'),
         tr=('Allahummə! Əuuzu biridaakə min səxatikə', 'əntə kəməə əsneytə aləə nəfsikə'),
         az=('note', 'Allahummə! Sənin qəzəbindən', 'Özünü öyüb-təriflədiyin kimisən!'), note=None),
    dict(cat=NS, sub='secdede-edilen-zikr', hid=747, sort=20,
         ar=('اللهم اجعل في سمعي نورا', 'واجعلني نورا'),
         tr=('Allahumməc’əl fii səm’ii nuran', 'vac\'əlnii nuran}'),
         az=('note', 'Allahummə! Eşitməyimdə', 'Mənim üçün bir nur et!'),
         note=('text_az', 'O, səcdələrində-və ya (belə) dedi: "namazında"-Şu\'bə şəkk etdi-(belə) deyirdi', None)),
    dict(cat=NS, sub='tesehhudde-oxunan-dua', hid=546, sort=10,
         ar=('اللهم اني اعوذ بك من عذاب جهنم', 'المسيح الدجال'),
         tr=('Allahummə innii əuuzu bikə min azəəbi Cəhənnəmə', 'fitnətil-məsihid-dəccəəli'),
         az=('note', 'Allahımmə! Şübhəsiz ki, mən Cəhənnəm əzabından', 'Sənə sığınıram'),
         note=('text_az', 'Sizdən biriniz (namazda) təşəhhüd edərkən dörd şeydən Allaha sığınsın', None)),
    dict(cat=NS, sub='namazda-edilen-dua', hid=547, sort=10,
         ar=('اللهم اني اعوذ بك من عذاب القبر', 'والمغرم'),
         tr=('Allahummə innii əuuzu bikə min azəəbil-qabri', 'minəl-mə\'səmi val-məğrami'),
         az=('note', 'Allahummə! Həqiqətən də, mən qəbr əzabından', '(və yaxud günaha və borca aparan şeydən) Sənə sığınıram!'),
         note=('text_az', 'İnsan borca girdikdə danışanda yalan deyər, söz verəndə də sözünün üstündə durmaz', None)),
    dict(cat=NS, sub='namazda-bir-sey-uz-verende', hid=3242, sort=10,
         ar=('من نابه شيء في صلاته فليسبح', None),
         tr=None,
         az=('text_az', 'Kimə namazında bir şey üz verərsə, (Allahı) təsbih etsin ("SubhənAllah"-desin)', None),
         note=('text_az', 'Əl çırpmaq (isə) yalnız qadınlara məxsusdur', None)),
    dict(cat=NS, sub='gece-namazinda-dua', hid=737, sort=10,
         ar=('اللهم لك الحمد انت قيم', 'لا اله الا انت'),
         tr=('Allahummə! Ləkəl-həmdu əntə qayyimus-səməəvaati', 'ləə iləəhə illəə əntə'),
         az=('note', 'Allahummə! Sənədir həmd! Sən səmaların', 'Səndən başqa ilah yoxdur!'), note=None),
    dict(cat=NS, sub='qunut', hid=611, sort=10,
         ar=('اللهم انج الوليد بن الوليد', 'كسني يوسف'),
         tr=None,
         az=('text_az', 'Allahummə! Valid ibnul-Validi, Sələmə ibn Hişamı və Ayyəş ibn əbi Rabianı', 'Yusufun (Misir xalqının yaşadığı qıtlıq illəri) illəri kimi et!'),
         note=('text_az', 'Rəsulullah sallallahu aleyhi və səlləm Sübh namazında son rükətdə (rükudan) başını qaldıranda, deyərdi', None)),
    dict(cat=NS, sub='qunut', hid=608, sort=20,
         ar=('اللهم العن بني لحيان', 'سالمها الله'),
         tr=None,
         az=('text_az', 'Allahummə! Allaha və Rəsuluna asi olan Bəni Lihyənə', 'Allah ona sülh, salamatlıq versin!'), note=None),

    # ---------------- İstiazə ----------------
    dict(cat='istiaze-dualari', sub=None, hid=1827, sort=90,
         ar=('اعوذ بوجهك', None),
         tr=None,
         az=('text_az', '(Allahummə! Bundan) Sənin Üzünə sığınıram!', None),
         note=None),

    # ---------------- Yağış, külək ----------------
    dict(cat='yagis-kulek-ve-bulud', sub=None, hid=677, sort=20,
         ar=('اللهم اسقنا', None, None),
         tr=None,
         az=('text_az', 'Allahummə! Bizə yağış yağdır!', None),
         note=None, rep=2),
    dict(cat='yagis-kulek-ve-bulud', sub=None, hid=678, sort=30,
         ar=('اللهم حوالينا ولا علينا', None),
         tr=None,
         az=('text_az', 'Allahummə! Ətrafımıza, üstümüzə yox', None), note=None),
    dict(cat='yagis-kulek-ve-bulud', sub=None, hid=3461, sort=40,
         ar=('اللهم اني اسالك خيرها', 'ما ارسلت به', None, 'من شرها'),
         tr=('Allahummə!İnnii əs\'əlukə xayrahəə', 'va şərri məə ursilət bihi'),
         az=('note', 'Allahummə! Həqiqətən də mən onun xeyrini', 'Sənə sığınıram!'),
         note=('text_az', 'Külək şiddətlə əsməyə başlayanda', None)),

    # ---------------- Xəstəlik və ruqyə ----------------
    dict(cat='xestelik-ve-ruqye', sub=None, hid=2913, sort=10,
         ar=('اللهم رب الناس', 'سقما'),
         tr=('Allahummə! Rabbən-nəəsi! Muzhibəl-bə\'si!', 'yuğaadiru səqamən!'),
         az=('LIT', ''),
         note=('text_az', 'Əbul-Qasim aleyhis-salətu vas-sələmin ruqyəsi ilə səni ruqyə etməyimmi?', None)),
    dict(cat='xestelik-ve-ruqye', sub=None, hid=2914, sort=20,
         ar=('بسم الله تربه ارضنا', 'باذن ربنا'),
         tr=('Bismilləhi, turbətu ərdınəə', 'biizni Rabbinəə'),
         az=('LIT', ''), note=None),
    dict(cat='xestelik-ve-ruqye', sub=None, hid=2915, sort=30,
         ar=('اعوذ بعزه الله وقدرته', 'ما اجد'),
         tr=None,
         az=('text_az', 'Onu (ağrıyan yerini) sağ əlinlə yeddi dəfə sürt və (belə) de', 'Onun qüdrətinə sığınıram'), note=None),
    dict(cat='xestelik-ve-ruqye', sub=None, hid=2917, sort=40,
         ar=('باسم الله ارقيك', 'باسم الله ارقيك'),
         tr=('Bismilləəhi ərqiikə', 'Bismilləəhi ərqiikə"'),
         az=('LIT', ''),
         note=('text_az', 'Cibril aleyhissələm Nəbi sallallahu aleyhi və səlləmin yanına gəlib dedi', None)),
    dict(cat='xestelik-ve-ruqye', sub=None, hid=2873, sort=50,
         ar=('اللهم اتنا في الدنيا حسنه', 'عذاب النار'),
         tr=None,
         az=('text_az', 'Allahummə! Bizə həm (bu) dünyada', 'Od əzabından qoru!'),
         note=('text_az', 'O, Allah azzə və cəlləyə dua etdi və Allah azzə və cəllə də ona şifa verdi', None)),

    # ---------------- Yemək ----------------
    dict(cat='yemek-ve-qonaqliq', sub=None, hid=2812, sort=20,
         ar=('اللهم اغفر لهم', 'في ارزاقهم'),
         tr=None,
         az=('text_az', 'Allahummə, onları bağışla, onlara rəhm et! Onlara bərəkət ver! Ruzilərində onlara genişlik ver!', None), note=None),
    dict(cat='yemek-ve-qonaqliq', sub=None, hid=3514, sort=30,
         ar=('اللهم اسق من سقاني', 'من اطعمني'),
         tr=None,
         az=('text_az', 'Allahummə!Məni içirdən kimsəni içirt və məni yedirdən kimsəni yedirt!', None), note=None),

    # ---------------- Həcc və Ümrə ----------------
    dict(cat='hecc-ve-umre', sub=None, hid=1021, sort=10,
         ar=('لبيك اللهم لبيك', 'والملك لا شريك لك'),
         tr=('Ləbbeykəllahummə ləbbeyk, ləbbeykə ləə şəriikə ləkə ləbbeykə', 'ləə şəriikə ləkə}}'),
         az=('note', 'Hüzurundayam, əmrindəyəm Allahummə', 'Sənin (heç bir) şərikin yoxdur!'), note=None),
    dict(cat='hecc-ve-umre', sub=None, hid=1031, sort=20,
         ar=('لبيك بحجه وعمره', None),
         tr=('Ləbbeykə bihəccətin va umratin məan!', None),
         az=('LIT', ''), note=None),
    dict(cat='hecc-ve-umre', sub=None, hid=1048, sort=30,
         ar=('اللهم محلي حيث حبستني', None),
         tr=None,
         az=('text_az', 'Allahummə! Harada məni həbs etsən, ora mənim ihramdan çıxdığım yerdir', None),
         note=('text_az', 'Həcc et və şərt qoş', None)),
    dict(cat='hecc-ve-umre', sub=None, hid=1072, sort=40,
         ar=('لا اله الا الله وحده لا شريك له له الملك', 'وهزم الاحزاب وحده', 'بدا بالصفا فرقي'),
         tr=('Ləə iləəhə illəllahu, vahdəhu ləə şəriikə ləhu. Ləhul-mulku', 'va həzəməl-əhzəəbə vahdəhu', 'Allahı tövhid etdi, Ona təkbir etdi'),
         az=('note', 'Allahdan başqa (heç bir) ilah yoxdur, O, təkdir', 'təkbaşına məğlub etdi'),
         note=('text_az', 'Sonra bunun arasında dua etdi, bunun mislini üç dəfə dedi', None)),
    dict(cat='hecc-ve-umre', sub=None, hid=1098, sort=50,
         ar=('اللهم ارحم المحلقين', None),
         tr=None,
         az=('text_az', 'Allahummə! (saçını) qırxanlara  rəhm et!', None), note=('text_az', '(Saçını) qısaldanlara da', None)),

    # ---------------- Düşmən qarşısında ----------------
    dict(cat='ehzab-gunu-nebi-sallallahu-aleyhi-ve-sellem-dusmene-qarsi-etdiyi-dua', sub=None, hid=451, sort=20,
         ar=('حبسونا عن الصلاه الوسطى', 'نارا'),
         tr=None,
         az=('text_az', 'Bizi orta namazdan-Əsr namazından-əngəllədilər', 'odla doldursun!'), note=None),
    dict(cat='dusmen-qarsisinda', sub=None, hid=2340, sort=10,
         ar=('اللهم منزل الكتاب', 'وانصرنا عليهم'),
         tr=None,
         az=('text_az', 'Allahummə! (Ey) Kitabı nazil edən!', 'bizə yardım et!'),
         note=('text_az', 'düşmənlə qarşı-qarşıya gəlməyi arzulamayın və Allahdan afiyət (salamatlıq) diləyin!', None)),
    dict(cat='dusmen-qarsisinda', sub=None, hid=2355, sort=20,
         ar=('لا اله الا الله وحده اعز جنده', 'فلا شيء بعده'),
         tr=('Ləə iləəhə illəllahu vahdəhu, əazzə cundəhu', 'fələə şey\'ə bə\'dəhu!'),
         az=('LIT', ''), note=None),
    dict(cat='dusmen-qarsisinda', sub=None, hid=1220, sort=30,
         ar=('اللهم نزل نصرك', None),
         tr=None,
         az=('text_az', 'Allahummə! Öz qələbəni (bizə) nazil et!', None),
         note=('text_az', 'Mən Nəbiyəm, yalan yoxdur!Mən Abdul-Muttalibin oğluyam!', None)),
    dict(cat='dusmen-qarsisinda', sub=None, hid=2404, sort=40,
         ar=('اللهم انك ان تشا', 'في الارض'),
         tr=None,
         az=('text_az', 'Allahummə! Əgər Sən istəsən yer üzündə Sənə ibadət edilməz', None), note=None),
    dict(cat='dusmen-qarsisinda', sub=None, hid=1253, sort=50,
         ar=('اللهم عليك الملا من قريش', 'امية بن خلف'),
         tr=None,
         az=('text_az', 'Allahummə!Qureyşin zadəganlarını Sənə həvalə edirəm!', 'Umeyyə ibn Xələfi}}'), note=None),
    dict(cat='dusmen-qarsisinda', sub=None, hid=1862, sort=60,
         ar=('اللهم سبع كسبع يوسف', None),
         tr=None,
         az=('text_az', 'Allahummə! Yusufun yeddisi kimi yeddi!', None), note=None),
    dict(cat='dusmen-qarsisinda', sub=None, hid=1634, sort=70,
         ar=('اللهم اصرعه', None),
         tr=None,
         az=('text_az', 'Allahummə! Onu yerə yıx (batır)', None), note=None),

    # ---------------- Şəxslər, qövmlər, yerlər ----------------
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=592, sort=10,
         ar=('اللهم اكثر ماله وولده', 'وبارك له فيه'),
         tr=None,
         az=('text_az', 'Allahummə! Onun malını və övladını çoxalt, onda ona bərəkət ver!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1636, sort=20,
         ar=('اللهم فقه في الدين', None),
         tr=None,
         az=('text_az', 'Allahummə! Onu dində fəqih et!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1588, sort=30,
         ar=('اللهم اجعله هاديا مهديا', None),
         tr=None,
         az=('text_az', 'Allahummə! Onu hidayət edən və hidayət olunmuş et!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=402, sort=40,
         ar=('اللهم ايده بروح القدس', None),
         tr=None,
         az=('text_az', 'Allahummə, onu Ruhul-Qüdslə dəstəklə!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1646, sort=50,
         ar=('اللهم اجعله منهم', None),
         tr=None,
         az=('text_az', 'Allahummə!Onu onlardan et!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1322, sort=60,
         ar=('اللهم اني احبه فاحبه', 'من يحبه'),
         tr=None,
         az=('text_az', 'Allahummə, həqiqətən də, mən onu sevirəm, Sən də onu sev və onu sevəni sev!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1317, sort=70,
         ar=('اللهم ارحمهما', 'ارحمهما'),
         tr=None,
         az=('text_az', 'Allahummə! Onlara rəhm et! (Çünki,) həqiqətən də, mən onlara rəhm edirəm!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=835, sort=80,
         ar=('اللهم صل على ال ابي اوفى', None),
         tr=('Allahummə! Salli aləə əəli əbi Əvfəə!', None),
         az=('text_az', '(Allahummə, Əbu Əvfənin ailəsinə xeyir et (ver)!)', None),
         note=('text_az', 'Bir ev əhli sədəqə (zəkat) ilə Rəsulullah sallallahu aleyhi və səlləmin yanına gələndə O, onlara dua edərdi', None)),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1732, sort=90,
         ar=('اللهم اغفر للانصار', None),
         tr=None,
         az=('text_az', 'Allahummə! Ənsarı, Ənsarın oğullarını (övladlarını) və Ənsarın oğullarının oğullarını, Ənsarın oğullarının qadınlarını, Ənsarın oğullarının oğullarının qadınlarını bağışla!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=399, sort=100,
         ar=('اللهم انه لا خير الا خير الاخره', 'والمهاجره'),
         tr=None,
         az=('text_az', 'Allahummə, həqiqətən də, axirət xeyrindən savayı xeyir yoxdur, Ənsar və Mühacirə yardım et!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=2100, sort=110,
         ar=('اللهم امض لاصحابي هجرتهم', 'على اعقابهم'),
         tr=None,
         az=('text_az', 'Allahummə! Əshabım üçün onların hicrətini tamamla və onları geri döndərmə!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1756, sort=120,
         ar=('اللهم اهد دوسا', 'وائت بهم'),
         tr=None,
         az=('text_az', 'Allahummə! Dovsa hidayət ver və onları (İslama və ya aramıza) gətir!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1733, sort=130,
         ar=('اللهم بارك لهم في مكيالهم', 'ومدهم'),
         tr=None,
         az=('text_az', 'Allahummə! Onların çəkilərində onlara  bərəkət ver! Onların sa\'ında və muddunda onlara bərəkət ver!', None), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=2174, sort=140,
         ar=('اللهم حبب الينا المدينه', 'الجحفه'),
         tr=None,
         az=('text_az', 'Allahummə! Məkkəni sevdiyimiz kimi', 'Cuhfəyə yönəlt!'), note=None),
    dict(cat='sexsler-qovmler-ve-yerler-ucun', sub=None, hid=1749, sort=150,
         ar=('اللهم بارك لنا في شامنا', 'في يمننا'),
         tr=None,
         az=('text_az', 'Allahummə! Bizə Şamımızda bərəkət ver! Allahummə! Bizə Yəmənimizdə bərəkət ver!', None), note=None),

    # ---------------- Xüsusi hallar ----------------
    dict(cat='xususi-hallarda-nebinin-sozleri', sub=None, hid=1327, sort=40,
         ar=('اللهم اني متخذ عندك عهدا', 'دعاء له'),
         tr=None,
         az=('text_az', 'Allahummə! Həqiqətən də, mən Səndən bir əhd alıram', 'bir dua et!'), note=None),

    # ---------------- Müxtəlif hallar ----------------
    dict(cat='muxtelif-hallarda', sub=None, hid=62, sort=30,
         ar=('امنا بالله', None),
         tr=None,
         az=('text_az', 'Sizdən kim belə bir şeylə qarşılaşsa: "Allaha iman etdik"-desin', None), note=None),

    # ---------------- Ölüm və son anlar ----------------
    dict(cat='olum-ve-son-anlar', sub=None, hid=1360, sort=10,
         ar=('اللهم اغفر لي وارحمني', 'بالرفيق الاعلى'),
         tr=('Allahumməğfir lii, varhəmnii, va əlhiqnii bir-Rafiiqil-Ə\'ləə', None),
         az=('note', 'Allahummə!Məni bağışla, mənə rəhm et və məni ən Uca Dosta qovuşdur!', None), note=None),
    dict(cat='olum-ve-son-anlar', sub=None, hid=1369, sort=20,
         ar=('اللهم الرفيق الاعلى', None),
         tr=('Allahummər-Rafiqal-Ə\'lə', None),
         az=('LIT', ''),
         note=('text_az', 'O, Onun danışdığı son kəlimədir', None)),
]
