package com.cafarovceyxun.anamuslim.db.kmp

import androidx.room.ConstructedBy
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

/**
 * Minimal KMP Room probe. It exists to prove the Room-KMP toolchain works in this project
 * (KSP native codegen, bundled SQLite driver, iOS linking, runtime round-trip) before the real
 * databases are moved to `commonMain`. The `expect object` + `@ConstructedBy` pair is the
 * reusable pattern every migrated database will follow.
 */
@Entity(tableName = "kmp_probe")
data class KmpProbeEntity(
    @PrimaryKey val id: Long,
    val value: String,
)

@Dao
interface KmpProbeDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(entity: KmpProbeEntity)

    @Query("SELECT * FROM kmp_probe WHERE id = :id")
    suspend fun get(id: Long): KmpProbeEntity?

    @Query("SELECT COUNT(*) FROM kmp_probe")
    suspend fun count(): Int
}

@Database(entities = [KmpProbeEntity::class], version = 1, exportSchema = false)
@ConstructedBy(KmpProbeDatabaseConstructor::class)
abstract class KmpProbeDatabase : RoomDatabase() {
    abstract fun probeDao(): KmpProbeDao
}

// The `actual` is generated by the Room compiler (KSP) for each target.
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpectedDeclaration")
expect object KmpProbeDatabaseConstructor : RoomDatabaseConstructor<KmpProbeDatabase> {
    override fun initialize(): KmpProbeDatabase
}
