# Hər dua: (alt başlıq, [seqmentlər], qeyd)
# seqment: (surə, ayə, ilk söz, son söz | None=ayənin sonu, tərcümə)
#   tərcümə: None = ayənin bütün tərcüməsi; ('başlanğıc', 'son') = həmin aralıq (daxil); '' = boş
#   ərəbcə sözlər uthmani yazısındandır (quranapp.db, script_id 1), ayə nömrəsi işarəsi sayılmır
# qeyd: None və ya (surə, ayə, 'başlanğıc', 'son') — kimin dediyi, ayənin öz tərcüməsindən
# parts: eyni duanın ayrı yerdən gələn davamı (ayrı sətir, part_of_id)
A = 'quran-allahin-istediyi-dualar'
D = [
 # --- Allahın etməyimizi istədiyi dualar ---
 dict(sub=A, segs=[(1,v,0,None,None) for v in range(1,8)]),
 dict(sub=A, segs=[(3,26,1,None,('Allahummə!', 'qadirsən!')), (3,27,0,None,None)]),
 dict(sub=A, segs=[(9,129,3,None,('Allah mənə yetər', 'Rəbbidir!'))]),
 dict(sub=A, segs=[(16,98,0,None,None)]),
 dict(sub=A, segs=[(17,24,7,None,('Rəbbim!', 'rəhm et!'))]),
 dict(sub=A, segs=[(17,80,1,None,('Rəbbim!', 'nəsib et!'))]),
 dict(sub=A, segs=[(17,111,1,18,('Həmd olsun', 'vəlisi də yoxdur!'))]),
 dict(sub=A, segs=[(18,23,0,None,None),(18,24,0,None,None)]),
 dict(sub=A, segs=[(20,114,14,None,('Rəbbim!', 'artır!'))]),
 dict(sub=A, segs=[(23,93,1,None,('Rəbbim!', 'göstərəcəksənsə!')),(23,94,0,None,None)]),
 dict(sub=A, segs=[(23,97,1,None,('Rəbbim!', 'sığınıram!')),(23,98,0,None,None)]),
 dict(sub=A, segs=[(23,118,1,None,('Rəbbim!', 'xeyirlisisən!'))]),
 dict(sub=A, segs=[(27,59,1,7,('Həmd olsun', 'qullarına!'))]),
 dict(sub=A, segs=[(33,56,0,None,None)]),
 dict(sub=A, segs=[(39,46,1,None,('Allahummə!', 'Sənsən!'))]),
 dict(sub=A, segs=[(43,13,11,None,('Bunları bizə ram edən', 'bilməzdik')),(43,14,0,None,('və şübhəsiz', 'qayıdacağıq'))],
      note=(43,13,'onların üstündə oturduğunuz zaman', '(xatırlayıb belə) deyəsiniz')),
 dict(sub=A, segs=[(47,19,0,9,('Bil ki,', 'bağışlanma dilə.'))]),
 dict(sub=A, segs=[(110,3,0,None,None)]),
 dict(sub=A, segs=[(113,v,0,None,None) for v in range(1,6)]),
 dict(sub=A, segs=[(114,v,0,None,None) for v in range(1,7)]),
 # --- Nəbilər ---
 dict(sub='quran-adem', segs=[(7,23,1,None,('Rəbbimiz!', 'olarıq!'))], note=(7,23,'O ikisi dedilər','O ikisi dedilər')),
 dict(sub='quran-nuh', segs=[(11,41,3,None,('Onun üzməsi', 'Rahimdir!'))], note=(11,41,'O, dedi: ”Minin ona!','O, dedi: ”Minin ona!')),
 dict(sub='quran-nuh', segs=[(11,47,1,None,('Rəbbim!', 'olaram!'))]),
 dict(sub='quran-nuh', segs=[(23,26,1,None,('Rəbbim!', 'yardım et!'))]),
 dict(sub='quran-nuh', segs=[(23,28,8,None,('Bizləri', 'həmd olsun!')),(23,29,1,None,('Rəbbim!', 'xeyirlisisən!'))],
      note=(23,28,'Sən və səninlə birlikdə olanlar','(belə) de')),
 dict(sub='quran-nuh', segs=[(26,117,1,None,('Rəbbim!', 'yalanladı!')),(26,118,0,None,('Ona görə də', 'xilas et!'))]),
 dict(sub='quran-nuh', segs=[(54,10,2,None,('Rəbbim!', 'yardım et!'))], note=(54,10,'O da öz Rəbbinə dua etdi ki','O da öz Rəbbinə dua etdi ki')),
 dict(sub='quran-nuh', segs=[(71,26,2,None,('Rəbbim!', 'qoyma!')),(71,27,0,None,None),(71,28,0,None,None)]),
 dict(sub='quran-ibrahim', segs=[(2,126,3,17,('Rəbbim!', 'ruziləndir!'))], note=(2,126,'Bir zaman İbrahim demişdi','Bir zaman İbrahim demişdi')),
 dict(sub='quran-ibrahim', segs=[(2,127,7,None,('Rəbbimiz!', 'Bilənsən)!')),(2,128,0,None,('Rəbbimiz!', 'Edənsən)!')),(2,129,0,None,None)],
      note=(2,127,'bir zaman İbrahim və İsmail', 'belə deyirdilər)')),
 dict(sub='quran-ibrahim', segs=[(14,35,3,None,('Rəbbim!', 'uzaq tut!'))]+[(14,v,0,None,None) for v in range(36,42)],
      note=(14,35,'Bir zaman İbrahim (dua edərək) demişdi','Bir zaman İbrahim (dua edərək) demişdi')),
 dict(sub='quran-ibrahim', segs=[(26,v,0,None,None) for v in range(83,90)]),
 dict(sub='quran-ibrahim', segs=[(37,100,0,None,None)]),
 dict(sub='quran-ibrahim', segs=[(60,4,45,None,('Rəbbimiz! Yalnız', 'dönüşümüz!')),(60,5,0,None,None)],
      note=(60,4,'Həqiqətən də, İbrahim və onunla birlikdə olanlarda','gözəl bir nümunə vardır')),
 dict(sub='quran-lut', segs=[(26,169,0,None,None)]),
 dict(sub='quran-lut', segs=[(29,30,1,None,('Rəbbim!', 'yardım et!'))]),
 dict(sub='quran-yusuf', segs=[(12,33,1,None,('Rəbbim!', 'olaram!'))]),
 dict(sub='quran-yusuf', segs=[(12,101,0,None,None)]),
 dict(sub='quran-sueyb', segs=[(7,89,30,None,('Biz yalnız Allaha', 'xeyirlisisən!'))]),
 dict(sub='quran-musa', segs=[(5,25,1,None,('Rəbbim!', 'arasını ayır'))]),
 dict(sub='quran-musa', segs=[(7,143,35,None,('Sən pak', 'ilkiyəm!'))], note=(7,143,'Özünə gəldikdə isə', 'dedi')),
 dict(sub='quran-musa', segs=[(7,151,1,None,('Rəbbim!', 'rəhmlisisən!'))]),
 dict(sub='quran-musa', segs=[(7,155,33,None,('Sənsən bizim Vəlimiz!', 'xeyirlisisən!')),(7,156,0,10,('Bizlərə', 'yönəldik!'))]),
 dict(sub='quran-musa', segs=[(10,88,2,None,('Rəbbimiz!', 'iman etməsinlər!'))]),
 dict(sub='quran-musa', segs=[(20,25,1,None,('Rəbbim!', 'genişləndir'))]+[(20,v,0,None,None) for v in range(26,33)]
      +[(20,33,0,None,None),(20,34,0,None,('və Səni', 'zikr edək!')),(20,35,0,None,None)]),
 dict(sub='quran-musa', segs=[(28,16,1,6,('Rəbbim!', 'bağışla məni!'))]),
 dict(sub='quran-musa', segs=[(28,21,5,None,('Rəbbim!', 'xilas et!'))], note=(28,21,'O, qorxu içində','çıxıb dedi')),
 dict(sub='quran-musa', segs=[(28,22,5,None,('Ola bilsin', 'yönəltsin'))], note=(28,22,'O, Mədyənə tərəf üz tutanda','dedi')),
 dict(sub='quran-musa', segs=[(28,24,7,None,('Rəbbim!', 'duyuram)'))]),
 dict(sub='quran-musa', segs=[(40,27,2,None,('Həqiqətən də mən', 'sığınmışam'))]),
 dict(sub='quran-suleyman', segs=[(27,19,5,None,('Rəbbim!', 'daxil et!'))]),
 dict(sub='quran-suleyman', segs=[(38,35,1,None,('Rəbbim!', 'Edənsən)!'))]),
 dict(sub='quran-eyyub', segs=[(21,83,4,None,('Rəbbim!', 'rəhmlisisən!'))], note=(21,83,'Bir zaman o, Rəbbinə nida (dua) etmişdi','Bir zaman o, Rəbbinə nida (dua) etmişdi')),
 dict(sub='quran-eyyub', segs=[(38,41,6,None,('Şeytan', 'toxundurmuşdur'))], note=(38,41,'Bir zaman o, Rəbbinə dua etmişdi','Bir zaman o, Rəbbinə dua etmişdi')),
 dict(sub='quran-yunus', segs=[(21,87,14,None,('Səndən başqa', 'idim!'))], note=(21,87,'(O, balığın qarnında)','etdi')),
 dict(sub='quran-zekeriyya', segs=[(3,38,5,None,('Rəbbim!', 'Edənsən)!'))]),
 dict(sub='quran-zekeriyya', segs=[(19,4,1,None,('Rəbbim!', 'olmadım!')),(19,5,0,None,''),(19,6,0,None,None)],
      note=(19,3,'Bir zaman o, öz Rəbbinə','(dua etmişdi).')),
 dict(sub='quran-zekeriyya', segs=[(21,89,4,None,('Rəbbim!', 'xeyirlisisən!'))]),
 dict(sub='quran-isa', segs=[(5,114,4,None,('Allahummə!', 'xeyirlisisən!'))], note=(5,114,'Məryəm oğlu İsa dedi','Məryəm oğlu İsa dedi')),
 dict(sub='quran-isa', segs=[(5,118,0,None,None)]),
 # --- Salehlər ---
 dict(sub='quran-salehler', segs=[(2,156,5,None,('Şübhəsiz ki', 'qayıdacağıq!'))], note=(2,156,'O kimsələr (o səbr edənlər)','deyirlər')),
 dict(sub='quran-salehler', segs=[(2,201,3,None,('Rəbbimiz!', 'qoru!'))], note=(2,201,'Onlardan kimisi','deyir')),
 dict(sub='quran-salehler', segs=[(2,250,5,None,('Rəbbimiz!', 'nəsib eylə!'))], note=(2,250,'Onlar Calut','dedilər')),
 dict(sub='quran-salehler', segs=[(2,285,21,None,('Eşitdik', 'dönüş(ümüz)!')),(2,286,12,None,('Rəbbimiz! Əgər', 'bizləri!'))],
      note=(2,285,'Rəsul, Rəbbindən','möminlər də.')),
 dict(sub='quran-salehler', segs=[(3,8,0,None,None),(3,9,0,None,None)]),
 dict(sub='quran-salehler', segs=[(3,16,2,None,('Rəbbimiz!', 'qoru!'))]),
 dict(sub='quran-salehler', segs=[(3,35,4,None,('Rəbbim!', 'Alimsən!'))], note=(3,35,'Bir zaman İmranın arvadı demişdi','Bir zaman İmranın arvadı demişdi'),
      parts=[dict(segs=[(3,36,14,None,('Həqiqətən də mən onu Məryəm', 'həvalə etdim!'))])]),
 dict(sub='quran-salehler', segs=[(3,53,0,None,None)]),
 dict(sub='quran-salehler', segs=[(3,147,6,None,('Rəbbimiz!', 'yardım et!'))]),
 dict(sub='quran-salehler', segs=[(3,173,13,None,('Allah bizə yetər', 'vəkildir!'))], note=(3,173,'O kimsələr ki','dedilər')),
 dict(sub='quran-salehler', segs=[(3,191,12,None,('Rəbbimiz!', 'qoru!'))]+[(3,v,0,None,None) for v in (192,193,194)],
      note=(3,191,'(Onlar) o kimsələr(dir) ki','təfəkkür etməkdədirlər.')),
 dict(sub='quran-salehler', segs=[(4,75,14,None,('Rəbbimiz!', 'göndər!'))]),
 dict(sub='quran-salehler', segs=[(5,83,16,None,('Ey Rəbbimiz!', 'bir yerə yaz!'))], note=(5,83,'(Allah tərəfindən)','görərsən.')),
 dict(sub='quran-salehler', segs=[(7,126,10,None,('Rəbbimiz!', 'öldür!'))]),
 dict(sub='quran-salehler', segs=[(10,85,1,None,('Biz yalnız', 'güc-qüvvət vermə)')),(10,86,0,None,('və Öz rəhmətinlə', 'xilas et!'))]),
 dict(sub='quran-salehler', segs=[(17,108,1,None,('Rəbbimiz pak', 'gələcəkdir!'))]),
 dict(sub='quran-salehler', segs=[(18,10,6,None,('Rəbbimiz!', 'üzərində et!'))], note=(18,10,'Bir zaman o gənclər','dedilər')),
 dict(sub='quran-salehler', segs=[(18,39,5,11,('MaşaAllah', 'məxsusdur)!'))], note=(18,39,'Məgər sən, öz bağına girdiyin zaman','Məgər sən, öz bağına girdiyin zaman')),
 dict(sub='quran-salehler', segs=[(19,18,1,None,('Əgər sən', 'sığınıram!'))], note=(19,18,'O (Məryəm), dedi','O (Məryəm), dedi')),
 dict(sub='quran-salehler', segs=[(23,109,6,None,('Rəbbimiz!', 'xeyirlisisən!'))], note=(23,109,'Həqiqətən də, Mənim qullarımdan bir dəstə vardı','deyirdilər')),
 dict(sub='quran-salehler', segs=[(25,65,2,None,('Rəbbimiz!', 'uzaqlaşmayandır!')),(25,66,0,None,None)]),
 dict(sub='quran-salehler', segs=[(25,74,2,None,('Rəbbimiz!', 'imam et!'))]),
 dict(sub='quran-salehler', segs=[(40,44,4,None,('Mən öz işimi', 'Görəndir)!'))]),
 dict(sub='quran-salehler', segs=[(46,15,21,None,('Rəbbim!', 'müsəlmanlardanam!'))], note=(46,15,'Nəhayət, o, yetkinlik','deyər')),
 dict(sub='quran-salehler', segs=[(59,10,5,None,('Rəbbimiz!', 'rəhmlisən)!'))], note=(59,10,'Onlardan sonra gələnlər','deyirlər')),
 dict(sub='quran-salehler', segs=[(66,8,34,None,('Rəbbimiz!', 'qadirsən!'))], note=(66,8,'O gün Allah Nəbini','yayılacaqdır.')),
 dict(sub='quran-salehler', segs=[(66,11,9,None,('Rəbbim!', '(də) xilas et!'))], note=(66,11,'Allah iman gətirənlərə','demişdi')),
 # --- Mələklər ---
 dict(sub='quran-melekler', segs=[(2,32,1,None,('Biz Səni', 'Sahibisən)!'))]),
 dict(sub='quran-melekler', segs=[(40,7,13,None,('Rəbbimiz!', 'qoru!')),(40,8,0,None,None),(40,9,0,None,None)],
      note=(40,7,'Ərşi daşıyanlar','bağışlanma diləyərlər')),
 # --- Cənnət əhli ---
 dict(sub='quran-cennet-ehli', segs=[(7,43,11,27,('Həmd olsun', 'gəlmişdilər'))]),
 dict(sub='quran-cennet-ehli', segs=[(10,10,0,None,None)]),
 dict(sub='quran-cennet-ehli', segs=[(35,34,1,None,('Həmd olsun', 'Verəndir)!')),(35,35,0,None,None)]),
 dict(sub='quran-cennet-ehli', segs=[(39,74,1,15,('Bizə', 'gözəldir!'))]),
 # --- Dua və zikr haqqında ---
 dict(sub='quran-dua-haqqinda', segs=[(2,152,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(2,186,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(7,55,0,None,None),(7,56,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(7,180,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(7,205,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(13,28,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(17,110,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(21,90,8,None,('Həqiqətən də onlar', 'itaət edənlər idilər.'))]),
 dict(sub='quran-dua-haqqinda', segs=[(27,62,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(33,41,0,None,None),(33,42,0,None,None)]),
 dict(sub='quran-dua-haqqinda', segs=[(40,60,0,None,None)]),
]
