# Mərhələ 3 maketi üçün məzmun: çıxarışlar (hər biri hədisin text_az-ının hərfi parçası olmalıdır — build yoxlayır)
# və zikrlər (ərəbcə xam text_ar-dan, oxunuş text_az-dan və ya «user» bayrağı ilə təklif, tərcümə kitabdan).
# Mənbə: Muheymin 1-ci cild, Namaz Kitabı, № 371–510.

# (açar) -> (cild, №, mətn)
EX = {
    # ---- Camaat namazı (№ 371–397, 403–419) ----
    'c_25': ('c1', 373, 'Camaat namazı sizin birinizin tək qıldığı namazdan iyirmi beş cüz əfzəldir'),
    'c_steps': ('c1', 372, 'elə bir addım atmaz ki, onunla onun dərəcəsi qaldırılmasın, onunla ondan bir günah silinməsin'),
    'c_wait': ('c1', 372, 'Sizdən biriniz namazı gözlədikcə namazdadır'),
    'c_isha_fajr': ('c1', 376, 'Əgər Atəmə və Sübhdə nə olduğunu bilsəydilər, sürünərək də olsa mütləq ona (o namazı qılmağa) gələrdilər'),
    'c_first_row': ('c1', 376, 'Əgər insanlar nidada (əzanda) və ilk səfdə nə olduğunu bilsəydilər'),
    'c_angels': ('c1', 375, 'Onlar Əsr namazında və Fəcr namazında toplaşırlar'),
    'c_nifaq': ('c1', 371, 'yalnız nifaqı (münafiqliyi) bilinən münafiqdən başqası ondan (camaat namazından) geri qalmazdı'),
    'c_carried': ('c1', 371, 'iki kişinin arasına daxil edilib (onlara söykənərək) səfə qoyulardı'),
    'imam_quran': ('c1', 385, 'ən çox Quran biləni (imam olaraq) önə çıxarın'),
    'imam_boy': ('c1', 385, 'Mən yeddi və ya səkkiz yaşlarımda onlara (namazda) imamlıq edirdim'),
    'imam_salim': ('c1', 386, 'Onların (arasında) Quranı ən çox biləni o idi'),
    'imam_oldest': ('c1', 387, 'sonra (da) ən böyüyünüz sizə (namazda) imamlıq etsin!'),
    'imam_like_me': ('c1', 387, 'Məni necə namaz qılan görürsünüzsə, elə də (məhz mən qıldığım kimi) namaz qılın!'),
    'light': ('c1', 381, 'Sizdən biri insanlara namaz qıldırdığı zaman yüngül qıldırsın, (çünki) həqiqətən də, onların içində zəif, xəstə və böyük (yaşlı, qoca) olanı var'),
    'light_alone': ('c1', 381, 'təkbaşına namaz qıldığı zaman isə, istədiyi qədər uzatsın'),
    'light_angry': ('c1', 383, 'Şübhəsiz ki, sizdən (sizin içinizdə belə etməklə insanları) nifrət etdirənlər var!'),
    'light_muadh': ('c1', 384, '"Vaşşəmsi va duhəhəə" və "Səbbihismə rabbikəl-ə\'lə" və onun kimi (surələri) oxu!'),
    'light_short': ('c1', 378, 'Rəsulullah sallallahu aleyhi və səlləm insanların (içində) camaat namazı ən xəfif olanı idi'),
    'walk': ('c1', 388, 'Yeriyərək gəlin, sükunətli olun. Çatdığınızı (imamla bərabər) qılın, çatmadığınızı da tamamlayın'),
    'dont_stand': ('c1', 392, 'Namaza iqamə verildiyi zaman məni görməmiş (namaz qılmaq üçün) ayağa durmayın'),
    'iqama_only': ('c1', 396, 'Təklikdə qıldığın namazlamı yoxsa bizimlə qıldığın namazla?'),
    'iqama_four': ('c1', 397, 'Sübh namazını dörd (rükət) qılırsan?!'),
    'follow': ('c1', 411, 'İmam yalnız ona tabe olunmaq üçün (təyin) edilmişdir. (Odur ki,) o rüku etdikdə siz də rüku edin, (rüküdan başını) qaldırdıqda siz də qaldırın!'),
    'follow_rabbana': ('c1', 412, '"Səmiallahu limən həmidəhu"-deyəndə, siz: "Rabbənə va ləkəl-həmdu"-deyin!'),
    'follow_sitting': ('c1', 412, 'Oturaraq qıldıqda siz də hamınız oturaraq qılın!'),
    'follow_last': ('c1', 412, 'Nəbi sallallahu aleyhi və səlləmin feillərindən (isə) yalnız ən sonuncusu götürülür'),
    'follow_after': ('c1', 414, 'Rəsulullah sallallahu aleyhi və səlləmi səcdə edən görmədikcə onlardan heç biri səcdə etməzdi'),
    'donkey': ('c1', 415, 'Namazında başını imamdan əvvəl qaldıran kimsə, Allahın onun surətini uzunqulaq surətinə çevirməsindən əmin olmaz'),
    'amin': ('c1', 416, 'siz də: "Əəmiin"-deyin'),
    'amin_angels': ('c1', 416, 'kimin sözü mələklərin sözü ilə üst-üstə düşsə, onun keçmiş günahları bağışlanar'),
    'ruku_complete': ('c1', 404, 'Rüku və səcdəni tamamlayın!'),
    'hamd_late': ('c1', 419, 'And olsun ki, on iki mələyin hansı biri onu (Allah dərgahına) qaldıracaq deyə yarışdıqlarını gördüm'),
    # Qunut (№ 420–427)
    'qunut_after': ('c1', 420, 'Bəli, rükudan sonra, azacıq'),
    'qunut_when': ('c1', 425, 'birinə bəddua və ya biri üçün dua etmək istədiyi zaman rükudan sonra qunut tutar'),
    'qunut_month': ('c1', 427, 'Rəsulullah sallallahu aleyhi və səlləm yalnız bir ay (boyunca) rükudan sonra qunut etdi'),
    'qunut_left': ('c1', 427, 'Nəbi sallallahu aleyhi və səlləm bir ay (boyunca) qunut (duası) etdi, sonra da onu (qunut etməyi) tərk etdi'),
    'qunut_ayah': ('c1', 423, 'Bu işin sənə aidiyyəti yoxdur'),
    'qunut_abuhurayra': ('c1', 424, 'Zöhr namazının, axırıncı İşanın və Sübh namazının son rükətində: "Səmiə\'llahu limən həmidəhu"-deyəndən sonra qunut tutar'),

    # ---- Səflər (№ 398–410) ----
    'row_or': ('c1', 399, 'Heç şübhəsiz ki, (ya) səflərinizi düzəldərsiniz, ya da heç şübhəsiz ki, Allah üzləriniz arasında (bir) müxalifət edər (aranıza ixtilaf qoyar)'),
    'row_arrows': ('c1', 399, 'Rəsulullah sallallahu aleyhi və səlləm səflərin arasını oxlar və mizraqlar (yan-yana qoyulub düzüldüyü) kimi düzəldərdi'),
    'row_then_takbir': ('c1', 399, 'biz (səflərimizdə) düz duranda isə təkbir edərdi'),
    'row_tight': ('c1', 400, 'Səflərinizi düzəldin və sıxlaşın'),
    'row_shoulder': ('c1', 400, 'onun çiyni yoldaşının (yanındakı adamın) çiyninə, ayağı ayağına yapışırdı'),
    'row_gaps': ('c1', 401, 'Səflərinizi sıxlaşdırın və aralarını yaxınlaşdırın və boyunları(nızı) bir hizada (bir xətt boyunca) tutun!'),
    'row_sees': ('c1', 402, 'mən sizi qarşımda necə görürəmsə, arxamda da elə görürəm'),
    'pos_one': ('c1', 408, 'O məni sağ tərəfinə qoydu'),
    'pos_one_woman': ('c1', 408, 'məni sağ tərəfinə qoydu, qadın isə bizim arxamızda namaz qıldı'),
    'pos_two_women': ('c1', 407, 'Ənəsi sağ tərəfinə qoydu, anası və xalasını isə onların (Rəsulullah sallallahu aleyhi və səlləm və Ənəsin) arxasında (səfə) qoydu'),
    'pos_two_boys': ('c1', 405, 'mən və bir yetim (uşaq) Onun arxasında səf tutduq (ikimiz bir cərgədə durduq), yaşlı qadın (Muleykə) da bizim arxamızda (durdu)'),
    'pos_women_behind': ('c1', 409, 'anam Ummu Suleym də (bizim) arxamızda idi'),
    'women_head': ('c1', 410, 'Kişilər (başlarını) qaldırmadıqca siz başlarınızı (səcdədən) qaldırmayın!'),

    # ---- Cümə (№ 428–464) ----
    'j_day': ('c1', 428, 'Sonra Allahın bizə fərz etdiyi bu gün ki var, Allah bizi ona hidayət etdi'),
    'j_hour': ('c1', 430, 'Cümədə (elə) bir saat (elə bir vaxt) vardır ki, o saatda namaz qıldığı halda Allahdan bir xeyir istəyən elə bir müsəlman yoxdur ki, Allah onu ona vermiş olmasın'),
    'j_hour_short': ('c1', 430, 'Onun az (bir vaxt) olduğunu deyir'),
    'j_ghusl': ('c1', 434, 'Sizdən biriniz cüməyə gəldiyi zaman qüsl etsin'),
    'j_ghusl_wajib': ('c1', 437, 'Cümə gününün qüslü bütün (hər bir) muhtəlimin (həddi-buluğa çatmış müsəlmanın) üzərinə vacibdir'),
    'j_ghusl_week': ('c1', 436, 'hər yeddi gündə (hər həftədə) bir gün yuyunsun'),
    'j_ghusl_umar': ('c1', 432, 'Üstəlik, hələ (sən təkcə) dəstəmaz (almısan)?'),
    'j_ghusl_why': ('c1', 441, 'Kaş ki, bu gününüz üçün təmizlənəydiniz'),
    'j_prep': ('c1', 439, 'Kim Cümə günü qüsl edib bacardığı qədər təmizlənər, sonra (da saç-saqqalını) yağlayar, və ya (evində olan) ətirlə ətirlənər'),
    'j_no_split': ('c1', 439, 'iki nəfərin arasını ayırmaz'),
    'j_pray': ('c1', 439, 'ona yazılmış (təqdir edilmiş qədər) namaz qılar'),
    'j_reward': ('c1', 439, 'onun onunla (o Cüməylə) digər Cümə arasındakı günahları bağışlanar'),
    'j_early': ('c1', 442, 'Kim Cümə günü cənabətdən qüsl etdiyi kimi qüsl edər, sonra ilk saatda (erkəndən Cümə namazını qılmağa) gedərsə sanki bir bədənə (bir dəvə) sədəqə etmiş kimidir'),
    'j_angels_listen': ('c1', 442, 'İmam (xütbə vermək üçün minbərə) çıxdığı zaman mələklər ora gələr, zikrə qulaq asarlar'),
    'j_pages': ('c1', 443, 'İmam (xütbə vermək üçün minbərə) çıxanda səhifələr bükülər'),
    'j_time': ('c1', 444, 'Biz Günəş meyl edəndə Rəsulullah sallallahu aleyhi və səlləm ilə birlikdə Cümə namazını qılırdıq'),
    'j_qailah': ('c1', 447, 'Biz Cümə namazından sonra Rəsulullah sallallahu aleyhi və səlləm ilə bərabər qailə edər və yemək yeyərdik'),
    'j_adhan': ('c1', 453, 'Cümə gününün (namazının) birinci əzanı imam minbərdə oturduğu zaman oxunardı'),
    'j_one_muezzin': ('c1', 453, 'Nəbi sallallahu aleyhi və səlləmin yalnız bir müəzzini vardı'),
    'j_two_khutbah': ('c1', 456, 'iki xütbə verirdi, bu ikisinin arasında (bir dəfə) otururdu'),
    'j_standing': ('c1', 456, 'Nəbi sallallahu aleyhi və səlləm (Cümə günü) ayaq üstə xütbə verirdi, sonra otururdu, sonra da ayağa qalxırdı'),
    'j_finger': ('c1', 455, 'O, musəbbihə (işarət, şəhadət) barmağı ilə işarə etdi'),
    'j_quiet': ('c1', 458, 'Cümə günündə, imam xütbə verərkən, sahibinə (yanında oturana): "Sus!"-desən, artıq boş danışmış olursan'),
    'j_tahiyya': ('c1', 460, 'Sizdən biriniz Cüməyə gələndə (görsə ki,) imam xütbə verir, (buna baxmayaraq) iki rükət namaz qılsın'),
    'j_tahiyya_ask': ('c1', 460, 'Namaz qıldınmı?'),
    'j_home_two': ('c1', 459, 'evinə qayıdar, iki rükət namaz qılar'),
    'j_not_four': ('c1', 459, 'Cümə namazını dörd rükət qılırsan?'),
    'j_two_rakah': ('c1', 461, 'bizə Cümə namazını qıldırdı və ilk səcdədə (birinci rükətdə) Cümə surəsini'),
    'j_surahs': ('c1', 464, 'Nəbi sallallahu aleyhi və səlləm Cümə namazında "Cümə" və "Munafiqun" surələrini oxuyardı'),
    'j_ghashiya': ('c1', 462, '"Həl ətəəkə" (Ğaşiyə surəsini) oxuyurdu'),
    'j_fajr': ('c1', 463, '"Əlif, ləəm, miim. Tənziil" və: "Həl ətəə"-ni (Səcdə və İnsan surələrini) oxuyardı'),
    'j_caravan': ('c1', 454, 'Rəsulullah sallallahu aleyhi və səlləm ilə bərabər on iki nəfər kişi qalana qədər insanlar ona (karvana) tərəf getdilər'),

    # ---- Səfər (№ 465–480) ----
    's_sadaqa': ('c1', 465, '(Bu) Allahın sizə sədəqə etdiyi sədəqədir, (elə isə) Onun sədəqəsini qəbul edin'),
    's_two': ('c1', 467, 'səfər namazı (olduğu kimi, iki rükət olaraq) iqrar edildi (saxlanıldı), hadarda olan namaza isə (müəyyən rükətlər) artırıldı'),
    's_safe': ('c1', 466, 'Sayımızın ən çox (olduğu) və tam əmin-amanlıqda olduğumuz halda Rəsulullah sallallahu aleyhi və səlləm bizlərə Minada namazı iki rükət (olaraq) qıldırdı'),
    's_town': ('c1', 472, 'Mədinədə Zöhr namazını dörd rükət qıldım, Zul-Huleyfədə isə Əsri iki rükət qıldım'),
    's_no_sunnah': ('c1', 471, 'nə əvvəlində, nə də sonrasında namaz qılmadılar'),
    's_complete': ('c1', 471, 'Əgər tətavvu etsəydim (fərz olmayan, sünnət namazlarını qılsaydım), şübhəsiz ki, (fərz namazları) tamamlayardım'),
    's_mina_osman': ('c1', 468, 'Kaş ki, dörd rükətdənsə, qəbul olunan iki rükətim olaydı'),
    's_khilaf': ('c1', 468, 'Xilaf (ixtilaf, təfriqə, bölücülük, ikitirəlik) daha şərlidir'),
    's_behind_imam': ('c1', 469, 'İbn Ömər imam ilə birlikdə namaz qılanda dörd rükət qılar, tək qılanda isə onu iki rükət qılardı'),
    's_zuhr_asr': ('c1', 475, 'Günəş meyl etməzdən əvvəl yola çıxanda Zöhrü Əsrin vaxtına qədər ertələyir, sonra (miniyindən) enib o ikisini birləşdirirdi'),
    's_zuhr_first': ('c1', 475, 'Günəş meyl edəndə isə, Zöhrü qılıb sonra (səfərə çıxmaq üçün miniyinə) minərdi'),
    's_maghrib_isha': ('c1', 477, 'Rəsulullah sallallahu aleyhi və səlləmi seyr (hər hansı bir iş üçün yola çıxmaq) tələsdirəndə Məğrib və İşanı cəm edirdi'),
    's_maghrib_late': ('c1', 478, 'İşa ilə onu cəm edənə (birləşdirənə) qədər Məğrib namazını ertələyirdi'),
    's_how': ('c1', 478, 'Məğribə iqamə verdirib onu üç (rükət) qılırdı, sonra salam verərdi, nadir hallarda bir az qalar, nəhayət İşaya iqamə verdirər və onu iki (rükət) qılardı, sonra salam verərdi'),
    's_hadar': ('c1', 480, 'Mən Mədinədə Nəbi sallallahu aleyhi və səlləm ilə birlikdə səkkiz (rükət) cəm edərək və yeddi (rükət) cəm edərək namaz qıldım'),
    's_ibnabbas': ('c1', 479, 'Rəsulullah sallallahu aleyhi və səlləmi gördüm, Zöhrü və Əsri, Məğrib və İşanı cəm etdi'),

    # ---- Bayram (№ 481–490) ----
    'e_days': ('c1', 481, 'Həqiqətən də, Allah onları sizin üçün daha xeyirli iki günlə dəyişdirmişdir;Fitr günü və Ədha günü'),
    'e_first': ('c1', 482, 'xütbədən qabaq namazla başladı'),
    'e_no_adhan': ('c1', 482, 'Nə Fitr günündə, nə də Ədha günündə (bayram namazı üçün) əzan verilmirdi'),
    'e_no_iqama': ('c1', 484, 'O (Abdullah ibn Abbas radıyallahu anhumə) əzan və iqaməni zikr etmədi'),
    'e_two': ('c1', 484, 'O, iki rükət (bayram) namaz(ı) qıldı, sonra xütbə verdi'),
    'e_musalla': ('c1', 486, 'Ədha (Qurban bayramı) günü və Fitr (Ramazan bayramı) günü (musalləyə) çıxar, (ilk olaraq) namazla başlayardı'),
    'e_face': ('c1', 486, 'qalxıb onlar musallədə oturmuş ikən, insanlara yönələrdi'),
    'e_standing': ('c1', 486, 'Nəbi sallallahu aleyhi və səlləm ayaq üstə duraraq xütbə verdi'),
    'e_sadaqa': ('c1', 486, 'Sədəqə verin, sədəqə verin, sədəqə verin!'),
    'e_marwan': ('c1', 486, 'Hardadır doğru yol? Namazla başlamaq hanı?'),
    'e_women_out': ('c1', 487, 'Həddi-bülüğa yeni çatmış qızları və evdə oturan qadınları (və ya ev qadınlarını musalləyə) çıxarın, qoy bayramda və müsəlmanların dua etməsində iştirak etsinlər'),
    'e_hayd': ('c1', 487, 'Heyzli qadınlar (isə) müsəlmanların musalləsindən uzaqda olsunlar'),
    'e_jilbab': ('c1', 488, 'Qoy rəfiqəsi ona (artıq qalan) paltar(lar)ından geyindirsin'),
    'e_women_sadaqa': ('c1', 489, 'Ey qadınlar topluluğu! Sədəqə verin'),
    'e_jewels': ('c1', 484, 'onlar da dərhal (əllərini) qulaqlarına və boyunlarına apardılar (sırğalarını və boyunbağılarını çıxardılar) və onları sədəqə etdilər'),
    'e_family': ('c1', 489, 'Sənin ərin və övladın, sədəqə verəcəyin kimsələrin buna ən haqlı olanlarıdırlar'),

    # ---- İstisqa (№ 491–498) ----
    'i_jumua': ('c1', 491, 'O, Cümə günü, minbərin üstündə ikən istisqa (yağış yağması üçün dua) etdi'),
    'i_ask': ('c1', 492, 'Mal(larımız) həlak oldu, əyal(ımız) ac qaldı, Allaha dua et, bizə yağış yağdırsın'),
    'i_rain': ('c1', 492, 'minbərindən enməmişdi ki, saqqalından yağış damcılamağa başladı'),
    'i_out': ('c1', 493, 'Rəsulullah sallallahu aleyhi və səlləm musalləyə çıxdı, istisqa edirdi, ridasını tərsinə çevirdi, qibləyə yönəldi və iki rükət namaz qıldı'),
    'i_back': ('c1', 493, 'O, dua etmək üçün arxasını camaata çevirib qibləyə üz tutduqdan sonra əbasını tərsinə çevirdi'),
    'i_then_pray': ('c1', 493, 'Bundan sonra bizə iki rükət namaz qıldırdı və hər iki rükətdə (surələri, təkbirləri) uca səslə etdi (oxudu)'),
    'i_armpit': ('c1', 494, 'Nəbi sallallahu aleyhi və səlləm (dua edərkən) əllərini (o qədər) qaldırdı ki, hətta qoltuq altının bəyazlığı göründü'),
    'i_only': ('c1', 494, 'Nəbi sallallahu aleyhi və səlləm duasında istisqadan başqa bir şeydə əllərini qaldırmırdı'),
    'i_palms': ('c1', 495, 'ovuclarının üstünü üzünə tərəf, içlərini isə yerə tərəf tutdu'),
    'i_other': ('c1', 497, 'Nəbi sallallahu aleyhi və səlləm əllərini (səmaya) qaldırıb iki dəfə (belə) dedi'),
    'i_abubakr': ('c1', 498, 'Əbu Bəkr əllərini (səmaya) qaldırıb Allaha həmd etdi'),

    # ---- Küsuf (№ 499–504) ----
    'k_signs': ('c1', 499, 'Şübhəsiz ki, Günəş və Ay kiminsə ölümünə və həyatına görə tutulmurlar. Lakin o ikisi Allah azzə və cəllənin ayətlərindən iki ayətdir. Bu baş verdikdə, o açılana kimi namaz qılın!'),
    'k_ibrahim': ('c1', 499, 'Günəş İbrahimin ölümünə görə tutuldu'),
    'k_do': ('c1', 500, 'əgər bunu (Günəş və ya Ayın tutulmasını) görsəniz Allaha dua edin, təkbir edin və sədəqə verin!'),
    'k_rows': ('c1', 500, 'insanları arxasında səflərə düzdü'),
    'k_how': ('c1', 500, 'O, qiyama durdu və qiyamı uzatdı, sonra rükuya getdi və rükunu uzatdı, sonra rükudan qalxdı və (bu dəfə də) qiyamı uzatdı, amma bu qiyam əvvəlkindən qısa idi, sonra (bir də) rükuya getdi və rükunu uzatdı, lakin bu, əvvəlki rükudan qısa idi, sonra (rükudan başını) qaldırdı və səcdə etdi'),
    'k_second': ('c1', 500, 'Sonra axırıncı rükətdə də onun (birinci rükətdə etdiklərinin) mislini etdi'),
    'k_four': ('c1', 500, 'dörd rüku və dörd səcdəni tamamladı'),
    'k_sajda': ('c1', 500, 'Sonra səcdə etdi və səcdələri uzatdı'),
    'k_khutbah': ('c1', 500, 'insanlara xütbə verdi, Allaha həmd-səna edib Onun şəninə təriflər etdi'),
    'k_until': ('c1', 500, 'sizdən (bu sıxıntı) qaldırılanadək namaz qılın'),
    'k_baqara': ('c1', 503, 'Bəqərə surəsini oxuyacaq qədər uzun (bir müddət) qiyamda qaldı'),
    'k_zikr': ('c1', 503, 'Bunların tutulduğunu gördüyünüz zaman dərhal Allahı zikr edin'),
    'k_itq': ('c1', 504, 'And olsun ki, Rəsulullah sallallahu aleyhi və səlləm Günəşin kusufu (tutulması) olduğu zaman bizə itəqanı əmr etdi'),
    'k_asma': ('c1', 501, 'Mən (də onunla birlikdə) namaza durdum'),

    # ---- Qorxu namazı (№ 505–510) ----
    'f1_one': ('c1', 505, 'Rəsulullah sallallahu aleyhi və səlləm Onunla birlikdə olanlarla bir rüku və iki səcdə etdi (bir rükət namaz qıldı)'),
    'f1_each': ('c1', 505, 'Sonra (oradakı) müsəlmanlardan hər bir kişi qalxıb özü üçün ayrı-ayrılıqda bir rüku edib iki səcdə etdi (qılmadığı bir rükəti hər kəs təklikdə qıldı)'),
    'f1_severe': ('c1', 506, 'Əgər qorxuları bundan daha da şiddətli olsa, o zaman yeriyərək, ayaq üstə duraraq və ya minik üstündə-qibləyə yönələrək və ya yönəlməyərək-(namazlarını) qılarlar'),
    'f2_guard': ('c1', 507, 'insanların hamısı namazda idilər, lakin onlar bir-birlərini (düşməndən) qoruyurdular'),
    'f3_qibla': ('c1', 508, 'düşmənlər onunla qiblənin arasında idilər, biz Onun arxasında iki səf durduq'),
    'f3_salam': ('c1', 508, 'Sonra (Nəbi sallallahu aleyhi və səlləm) salam verdi və bizim də hamımız (Onunla birlikdə) salam verdik'),
    'f4_four': ('c1', 509, 'Rəsulullah sallallahu aleyhi və səlləm dörd rükət namaz qıldı, qövm (oradakı camaat) isə iki rükət qıldılar'),
    'f5_one': ('c1', 510, 'Rəsulullah sallallahu aleyhi və səlləm iki rükət namaz qıldı, qövm (oradakı camaat) bir rükət bir rükət qıldılar'),
    'f5_qasr': ('c1', 510, 'qəsr yalnız döyüş vaxtı (qılınan) bir rükətdir'),
}

# Zikrlər. ar — xam text_ar-dan (hərəkə qatlanaraq yoxlanır); tr — text_az-da axtarılır, «user» olanda təklifdir və
# maketdə təsdiq qutusu ilə görünür; mean — kitabdan (meanSrc yeri göstərir).
ZK = {
    'amin': {'ref': ('c1', 416), 'ar': 'آمِينَ', 'tr': 'Əəmiin', 'mean': '', 'meanSrc': 'kitabda tərcümə yoxdur',
             'where': 'İmam «Valəd-daalliin» deyəndə'},
    'rabbana': {'ref': ('c1', 416), 'ar': 'اللَّهُمَّ رَبَّنَا لَكَ الْحَمْدُ', 'tr': 'Allahummə, Rabbənə ləkəl-həmdu',
                'mean': 'Allahummə, Rəbbimiz, Sənədir həmd!', 'meanSrc': '№ 327-nin izahı', 'where': 'İmam «Səmiallahu limən həmidəh» deyəndə'},
    'hamd': {'ref': ('c1', 419), 'ar': 'الْحَمْدُ لِلَّهِ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ', 'tr': 'Əlhəmdu lilləhi, həmdən kəsiran tayyibən mubərakən fihi',
             'mean': 'Həmd Allaha məxsusdur, çoxlu, xoş, mübarək bir həmd', 'meanSrc': 'hədisin qeydi', 'where': 'Səfə tələsik qoşulan kişi dedi'},
    'isqina': {'ref': ('c1', 491), 'ar': 'اللَّهُمَّ اسْقِنَا', 'tr': 'Allahummə-sqinə', 'user': True,
               'mean': 'Allahummə! Bizə yağış yağdır!', 'meanSrc': 'hədisin mətni', 'where': 'İki dəfə dedi'},
    'hawalayna': {'ref': ('c1', 491), 'ar': 'اللَّهُمَّ حَوَالَيْنَا وَلَا عَلَيْنَا', 'tr': 'Allahummə həvələynə va lə aleynə', 'user': True,
                  'mean': 'Allahummə! Ətrafımıza, üstümüzə yox!', 'meanSrc': 'hədisin mətni', 'where': 'Yağış çox olanda'},
}

# Hədis vərəqində göstəriləcək əlavə istinadlar (çıxarışı olmayanlar).
EXTRA_REFS = [('c1', n) for n in (374, 377, 380, 382, 389, 390, 391, 393, 394, 395, 398, 403, 406, 413, 417, 418, 421, 422, 426,
                                  429, 431, 433, 435, 438, 440, 445, 446, 448, 449, 450, 451, 452, 457, 463, 470, 473, 474, 476,
                                  483, 485, 490, 496, 503)]
