# Mərhələ 4 maketi üçün məzmun: çıxarışlar (hər biri hədisin text_az-ının və ya qeydinin hərfi parçası olmalıdır —
# build yoxlayır) və zikrlər (ərəbcə, oxunuş və tərcümə kitabdan, lövbərlə kəsilir, əl ilə yazılmır).
# Mənbə: Muheymin 1-ci cild, Namaz Kitabı, № 511–595 (bazada № 559 yoxdur).

# (açar) -> (cild, №, mətn)
EX = {
    # ---- Sünnət namazları (№ 511–526) ----
    'r_12': ('c1', 511, "Kim bir gündə tətavvu' olaraq on iki səcdə (rükət) namaz qılsa, Cənnətdə onun üçün bir ev tikilər"),
    'r_12_kept': ('c1', 511, 'O vaxtdan bəri mən onları qılmağa davam edirəm'),
    'r_ten': ('c1', 512, 'Nəbi sallallahu aleyhi və səlləmdən on rükət (sünnət namazı qılmasını) hifz etdim (əzbərlədim)'),
    'r_list': ('c1', 512, 'Zöhrdən əvvəl iki rükət, sonra da iki rükət, Məğribdən sonra evində iki rükət, İşadan sonra (da) iki rükət evində və iki rükət də Sübh namazından əvvəl'),
    'r_jumuah': ('c1', 512, 'Cümədən (Cümə namazından) sonra isə (evinə) gedib iki rükət namaz qılmadan (başqa) namaz qılmırdı'),
    'f_never': ('c1', 514, 'İki rükət (namaz) var ki, Rəsulullah sallallahu aleyhi və səlləm nə gizlində, nə də aşkarda heç vaxt (onu) tərk etməmişdir'),
    'f_eager': ('c1', 522, 'Rəsulullah sallallahu aleyhi və səlləmin, Fəcrin iki rükətinə və qənimətə tələsdiyi kimi nafilələrdən heç birinə tələsdiyini görmədim'),
    'f_light': ('c1', 523, 'Sübh namazında, nida və iqamə arasında xəfif iki rükət namaz qılırdı'),
    'f_fatiha': ('c1', 525, 'Görəsən onda (namazda) kitabın Fatihəsini oxudumu?'),
    'f_ayah1': ('c1', 526, 'Biz Allaha, bizə nazil edilənə və İbrahimə və İsmayıla nazil edilənə iman etdik'),
    'f_ayah2': ('c1', 526, 'Allaha iman etdik və bizə şahid ol ki, biz müsəlmanlarıq'),
    'f_lie': ('c1', 524, 'mən oyaq olsam mənimlə danışar, olmasam namaza qalxana qədər uzanardı'),
    'f_right': ('c1', 556, 'Sonra müəzzin onun yanına iqamə oxumağa gələnədək sağ böyrü üstə uzanardı'),
    'asr_two': ('c1', 513, 'Rəsulullah sallallahu aleyhi və səlləm mənim yanımda Əsrdən sonra (qıldığı) iki rükəti əsla tərk etmədi'),
    'asr_masjid': ('c1', 515, 'ümmətinə ağırlaşdırılma qorxusu ilə onu məsciddə qılmazdı'),
    'nahy': ('c1', 516, 'Əsrdən sonra Günəş batanadək və Sübhdən sonra Günəş çıxanadək namaz qılmağı nəhy (qadağan) etdi'),
    'between': ('c1', 518, 'Bütün (hər) iki əzan (əzan və iqamə) arasında istəyən kimsə üçün (qılacağı) namaz vardır'),
    'maghrib_rush': ('c1', 519, 'Rəsulullah sallallahu aleyhi və səlləmin əshabı qalxıb sütunlara (doğru) tələsərdilər'),
    'maghrib_many': ('c1', 520, 'o iki rükəti qılanların çoxluğundan, heç şübhəsiz, elə hesab edərdi ki, artıq (Məğrib) namaz(ı) qılınmışdır'),
    'maghrib_busy': ('c1', 521, 'Həqiqətən də, biz onu Rəsulullah sallallahu aleyhi və səlləmin zamanında edirdik'),

    # ---- Duha və digər nafilələr (№ 527–539) ----
    'duha_will': ('c1', 527, 'Yuxudan əvvəl vitr, iki rükət Duha namazı və hər ayda üç gün oruc (tutmaq)'),
    'duha_eight': ('c1', 528, 'bir (qat) örtüyə bürünmüş halda səkkiz rükət namaz qıldı'),
    'duha_time': ('c1', 528, 'Bu (söhbət), duha vaxtında olmuşdur'),
    'duha_full': ('c1', 529, 'lakin O, rüku və səcdələri tamamlayırdı'),
    'duha_anas': ('c1', 530, 'Onun həmin gündən başqa onu (Duha namazını) qıldığını görmədim'),
    'duha_aisha': ('c1', 531, 'Rəsulullah sallallahu aleyhi və səlləm bir əməli etməyi sevdiyi halda onu tərk edirdi'),
    'duha_aisha_pray': ('c1', 531, 'şübhə yoxdur ki, həqiqətən də, mən onu qılıram'),
    'duha_umar': ('c1', 532, 'Onu(n da qıldığını) zənn etmirəm'),
    'duha_note': ('c1', 532, 'Əbu Hureyrə və Əbu Zər hədislərindən açıq-aydın şəkildə bilinir ki, Rəsulullah sallallahu aleyhi və səlləm ümmətini bu namaza irşad etmişdir'),
    'return_two': ('c1', 533, 'Məscidə daxil ol və iki rükət namaz qıl'),
    'bilal': ('c1', 534, 'tam bir təharətlə təmizləndiyim elə bir saat (elə bir vaxt) olmadı ki, (o vaxtda) Rəbbim üçün mənə təqdir edilmiş (qədər) namaz qılmış olmayam'),
    'home': ('c1', 535, 'Ey insanlar, evinizdə namaz qılın! Çünki fərz namazdan başqa ən fəzilətli namaz insanın evində qıldığı namazdır'),
    'able': ('c1', 537, 'Əməllərdən taqətiniz yetdiyini edin! Şübhəsiz ki, siz yorulmadıqca, Allah (da) yorulmaz'),
    'lasting': ('c1', 537, 'Həqiqətən də, Allaha ən sevimli (olan) əməl(iniz), az da olsa (edilməyə) davam ediləndir'),
    'hush': ('c1', 538, 'Sus! Siz (əməllərdən) güc çatdırdığınızı edin!'),
    'zaynab': ('c1', 539, 'Biriniz özünü gümrah hiss etdikcə namazını qılsın, yorulduqda isə otursun'),

    # ---- Gecə namazı və vitr (№ 540–569) ----
    'knots_say': ('c1', 540, 'Qarşında uzun gecə var, yat!'),
    'knots': ('c1', 540, 'Əgər o (kimsə) oyanıb Allahı zikr etsə, (o düyünlərdən) bir düyün açılar, əgər dəstəmaz alsa, (ikinci) bir düyün də açılar, əgər namaz qılsa, (üçüncü) bir düyün də açılar'),
    'slept': ('c1', 541, 'Şeytan onun qulağına bövl edib'),
    'dawud': ('c1', 543, 'Namazın Allaha ən sevimlisi Davudun namazıdır, gecənin yarısını yatar, üçdə birini namaz qılar, altıda birini yatardı'),
    'rights': ('c1', 544, 'Namaz qıl, həm də yat, oruc tut, həm də iftar et'),
    'rooster': ('c1', 549, 'Sarixin (xoruzun) səsini eşidəndə qalxardı'),
    'first_last': ('c1', 550, 'O, gecənin əvvəlində yatar, axırında isə qalxardı'),
    'two_two': ('c1', 552, 'Gecə namazı iki ikidir, Sübhün (Sübh namazının girməsindən) qorxduqda, bir rükətlə vitr et'),
    'witr_one': ('c1', 553, 'Vitr gecənin axırında (qılınan) bir rükətdir'),
    'witr_last': ('c1', 569, 'Gecə (qıldığınız) namaz(lar)ınızın ən sonuncusunu vitr edin!'),
    'witr_any': ('c1', 568, 'gecənin əvvəlində, ortasında və axırında. Onun vitri səhərə qədər çəkirdi'),
    'eleven': ('c1', 554, 'Ramazanda və başqasında (nə Ramazanda, nə də başqa aylarda) on bir rükətdən artıq (gecə) namaz(ı) qılmırdı'),
    'four_four': ('c1', 554, '(Əvvəlcə) dörd (rükət) qılırdı ki, onların gözəlliyini və uzunluğunu heç soruşma'),
    'eyes': ('c1', 554, 'Ey Aişə, həqiqətən də, mənim gözlərim yatır, (lakin) qəlbim yatmır'),
    'salam_each': ('c1', 556, 'hər iki rükətdə salam verər, bir rükətlə də vitr edərdi'),
    'sajda_fifty': ('c1', 556, 'Başını qaldırmamışdan əvvəl səcdəsində sizlərdən biri əlli ayə oxuyacaq (vaxt) qədər qalardı'),
    'thirteen': ('c1', 558, 'Rəsulullah sallallahu aleyhi və səlləmin gecə namazı on rükət idi, bir səcdə ilə vitr edər'),
    'zayd': ('c1', 555, 'Sonra (gecə namazına başlayaraq) iki çox uzun rükət qıldı'),
    'six_pairs': ('c1', 562, 'İki rükət namaz qıldı, sonra iki rükət qıldı, yenə iki rükət qıldı, bir də iki rükət qıldı, sonra yenə iki rükət qıldı, bir daha iki rükət qıldı, sonra da tək rükət namaz (vitr) qıldı'),
    'five': ('c1', 560, 'O məni sağ tərəfinə keçirtdi və beş rükət namaz qıldı. Sonra da iki rükət qıldı'),
    'wipe': ('c1', 562, 'oturub əli ilə üzündəki yuxunu silməyə başladı'),
    'ali_imran': ('c1', 562, 'Ali-İmran surəsinin sonundakı on ayəni oxudu'),
    'sky': ('c1', 563, 'səmaya baxdı, sonra Ali-İmrandakı bu ayəni'),
    'miswak': ('c1', 563, '(dişlərini) misvakladı və dəstəmaz aldı, sonra qalxıb namaz qıldı'),
    'right_side': ('c1', 564, 'Məni sağ tərəfinə keçirmək üçün əli ilə arxamdan (və ya arxasından) işarə etdi'),
    'ramadan_fear': ('c1', 536, 'Şübhəsiz ki, gecə (qiyamul-leyl) namazının sizə yazılacağından (fərz ediləcəyindən) qorxdum'),
    'tartil': ('c1', 565, '(Namazında oxuduğu) surəni tərtillə oxuyurdu'),
    'sitting': ('c1', 566, 'rüku etmək istədikdə, ayağa qalxıb otuz və ya qırx ayə oxuduqdan sonra rüku edərdi'),
    'sleep_after': ('c1', 547, 'Mən Rəsulullah sallallahu aleyhi və səlləmi öz yanımda son səhər vaxtında yalnız yatmış olduğu halda gördüm'),
    'wake_witr': ('c1', 594, 'vitr etmək istədikdə məni oyadardı, (mən də qalxıb) vitr edərdim'),

    # ---- Səhv səcdəsi (№ 570–575) ----
    'shaytan': ('c1', 570, 'onun heç ağlına belə gəlməyən şeyləri ona o qədər xatırladar ki, həmin kişi (adam) neçə (rükət) qıldığını bilməz'),
    'sit_two': ('c1', 571, 'oturduğu halda iki səcdə etsin'),
    'yaqin': ('c1', 572, 'şəkki atsın (buraxsın, namazını qəlbində, zehnində) yəqin olan üzərində bina etsin. Sonra salam verməzdən əvvəl iki səcdə etsin'),
    'yaqin_why': ('c1', 572, 'Əgər beş (rükət) qılmış olsa, (bu iki səcdə) onun namazını cüt edər, əgər dördü tamamlamaq üçün qılsa, (bu iki səcdə) şeytan üçün burnunun yerə sürtülməsi olar'),
    'taharri': ('c1', 573, 'Sizdən biriniz bir namazda səhv etsə, qoy doğrunu araşdırsın və onun üzərində (namazını) tamamlasın. Salam verdikdə isə, iki səcdə edər'),
    'human': ('c1', 573, 'Lakin mən (də) bir bəşərəm, siz unutduğunuz kimi (mən də) unuduram. (Odur ki,) mən unutduqda mənə (bunu) xatırladın'),
    'extra_after': ('c1', 573, 'O da salam verdikdən sonra iki səcdə etdi'),
    'extra_then_salam': ('c1', 573, 'O, ayağını bükdü və iki səcdə etdi, sonra da salam verib üzünü insanlara çevirib dedi'),
    'dhul_q': ('c1', 574, 'Namaz qısaldı yoxsa unutdun ya Rəsulallah?'),
    'dhul': ('c1', 574, 'Rəsulullah sallallahu aleyhi və səlləm qalxıb digər iki rükəti qıldı, sonra salam verdi, sonra təkbir edib (namazdakı) səcdələrinin mislində və ya daha uzun səcdə etdi'),
    'dhul_talk': ('c1', 574, 'Nəbi sallallahu aleyhi və səlləm salam verdikdən və danışdıqdan sonra o ikisini (iki səhv səcdəsini) etdi'),
    'tash_forgot': ('c1', 575, 'Rəsulullah sallallahu aleyhi və səlləm bizə iki rükət namaz qıldırdı, sonra qalxdı və (təşəhhüd üçün) oturmadı'),
    'tash_fix': ('c1', 575, 'O, salamdan əvvəl təkbir etdi, sonra oturduğu halda iki səcdə etdi, sonra da salam verdi'),

    # ---- Tilavət səcdəsi (№ 576–579) ----
    't_out': ('c1', 576, 'namazdan xaric (Quran oxuyarkən) səcdə (ayəsi) oxuyur, səcdə edir, biz də Onunla birlikdə səcdə edirdik'),
    't_crowd': ('c1', 576, 'hətta bizdən biri alnını qoymağa yer tapmırdı'),
    't_najm': ('c1', 577, 'Nəbi sallallahu aleyhi və səlləm Məkkədə Nəcm surəsini oxudu və onda səcdə etdi, Onunla birlikdə olanlar da səcdə etdilər'),
    't_isha': ('c1', 578, 'Əbul-Qasim sallallahu aleyhi və səlləmin arxasında onda (İnşiqaq surəsində) səcdə etdim'),
    't_late': ('c1', 579, 'Əbu Hureyrə Xeybər ilində, altıncı ildə müsəlman olmuşdur və Rəsulullah sallallahu aleyhi və səlləmdən olan bu səcdələr Onun sonda (ömrünün sonlarında) etdiyidir'),

    # ---- Cənazə (№ 580–595) ----
    'qirat': ('c1', 583, 'Kim bir cənazəyə namaz qılarsa, ona bir qirat vardır, kim də (o dəfn olunub) bitirilənədək gözləsə, onun üçün iki qirat vardır'),
    'qirat_mount': ('c1', 583, 'İki əzəmətli dağ mislindədir'),
    'qirat_lost': ('c1', 583, 'And olsun ki, çoxlu qiratlar zay etmişik'),
    'wash': ('c1', 580, 'Onu üç, yaxud beş, yaxud da daha artıq (sayda) su və sidr ilə yuyun, axırıncıda (son yumada suya) kafur əlavə edin'),
    'wash_odd': ('c1', 580, 'Onu tək sayda yuyun;üç və ya beş və ya yeddi dəfə'),
    'wash_start': ('c1', 580, 'Onun sağ tərəflərindən və dəstəmaz yerlərindən başlayın'),
    'shroud': ('c1', 580, 'Onu ona bükün'),
    'hair': ('c1', 581, 'Biz onun saçlarını üç hörük hörüb arxasına (kürəyinə) atdıq'),
    'graves': ('c1', 582, 'Qəbirlərin üstündə oturmayın və onlara tərəf namaz qılmayın!'),
    'debt': ('c1', 584, 'Borcunu ödəmək üçün vəfa (mal) qoyub gedibmi?'),
    'debt_pray': ('c1', 584, 'Dostunuza (cənazə) namaz(ını özünüz) qılın'),
    'debt_mine': ('c1', 584, 'möminlərdən kim ölsə və (özündən sonra ödəyəcək) borc qoyub getsə, onun ödənməsi mənim öhdəmdədir'),
    'abu_qatada': ('c1', 585, 'Ya Rəsulallah, Sən ona (cənazə) namazı qıl, mən onun borcunu öz öhdəmə götürürəm'),
    'munafiq': ('c1', 587, 'Heç vaxt onlardan ölmüş bir kəsin cənazə namazını qılma, qəbrinin başında da durma'),
    'four': ('c1', 588, 'onlarla musalləyə çıxdı, onları səflərə düzdü və dörd (dəfə) təkbir etdi'),
    'four_short': ('c1', 588, 'Nəbi sallallahu aleyhi və səlləm Nəcaşiyə dörd təkbir etdi'),
    'istighfar': ('c1', 588, 'Qardaşınız üçün bağışlanma diləyin!'),
    'abroad': ('c1', 589, 'Ölkənizdən (şəhərinizdən) kənarda ölən qardaşınız üçün namaz qılın!'),
    'row23': ('c1', 589, 'Mən də ikinci və ya üçüncü səfdə idim'),
    'fatiha': ('c1', 590, 'Bu, haqq və sünnətdir'),
    'fatiha_why': ('c1', 590, 'bilsinlər ki, o, (cənazə namazında Fatihə surəsini oxumaq) sünnətdir'),
    'grave': ('c1', 591, 'onları arxasında səflərə düzdü və ona (qəbirdə dəfn olunan adama) namaz qıldı'),
    'grave_take': ('c1', 592, 'Məni onun qəbrinə aparın'),
    'grave_light': ('c1', 592, 'Həqiqətən də, bu qəbirlər əhlinin üstünə (dolan, çökən) zülmətlə doludur və şübhəsiz ki, Allah azzə və cəllə mənim onlara olan namazım ilə onlar üçün bunları (bu qəbirləri) nurlandırır'),
    'uhud': ('c1', 593, 'dirilərə və ölülərə vida edən biri kimi, səkkiz ildən sonra Uhudda öldürülənlərə namaz qıldı'),
    'place': ('c1', 594, 'Mən Onunla qiblə arasında, cənazənin uzadılması kimi uzanmış ikən, Nəbi sallallahu aleyhi və səlləm gecə namazını qılardı'),
    'aisha_woman': ('c1', 594, 'And olsun ki, mən Rəsulullah sallallahu aleyhi və səlləmin qarşısında cənazənin uzadılması kimi uzanmış vəziyyətdə ikən O namaz qılırdı'),
}

# Zikrlər: ərəbcə xam text_ar-dakı {…} blokundan, oxunuş text_az-dakı {…} blokundan (lövbərlə tapılır),
# tərcümə hədisin qeydindən (meanFrom … meanTo arası). Heç biri əl ilə yazılmır.
ZK = {
    'tahajjud': {'ref': ('c1', 551), 'arAnchor': 'اللهم لك الحمد انت قيم', 'trAnchor': 'Allahummə! Ləkəl-həmdu əntə qayyimus',
                 'meanFrom': 'Allahummə! Sənədir həmd!', 'meanTo': 'Səndən başqa ilah yoxdur!',
                 'alt': {'arAnchor': 'لا اله غيرك', 'trAnchor': 'Ləə iləəhə ğayrukə', 'mean': 'Səndən qeyri ilah yoxdur!'},
                 'where': 'Gecə qalxıb təhəccüd edəndə', 'foot': True},
    'nur': {'ref': ('c1', 561), 'arAnchor': 'اللهم اجعل في سمعي نورا', 'trAnchor': 'Allahumməc’əl fii səm’ii nuran',
            'meanFrom': 'Allahummə! Eşitməyimdə (qulağımda) nur et!', 'meanTo': 'Mənim üçün bir nur et!"',
            'where': 'Səcdələrində və ya namazında (Şu‘bə şəkk etdi)'},
    'sajda': {'ref': ('c1', 567), 'arAnchor': 'اللهم اعوذ برضاك', 'trAnchor': 'Allahummə! Əuuzu biridaakə',
              'meanFrom': 'Allahummə! Sənin qəzəbindən', 'meanTo': 'Özün Özünü öyüb-təriflədiyin kimisən!',
              'where': 'Gecə səcdədə'},
}

# Hədis vərəqində göstəriləcək bütün istinadlar (bu mərhələnin hamısı; № 559 bazada yoxdur).
EXTRA_REFS = [('c1', n) for n in range(511, 596) if n != 559]
