package com.cafarovceyxun.anamuslim.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.cafarovceyxun.anamuslim.db.dao.AtlasWordShapeDao
import com.cafarovceyxun.anamuslim.db.dao.WbwDao
import com.cafarovceyxun.anamuslim.db.entities.atlas.AtlasBundleEntity
import com.cafarovceyxun.anamuslim.db.entities.atlas.AtlasWordShapeEntity
import com.cafarovceyxun.anamuslim.db.entities.wbw.WbwAudioTimingEntity
import com.cafarovceyxun.anamuslim.db.entities.wbw.WbwWordEntity

// NOTE: the former `@TypeConverters(QuranConverters)` was dropped — none of this database's
// entities use the enum types it converts (those belong to QuranDatabase). QuranConverters
// stays in the app module for QuranDatabase.
@Database(
    entities = [
        WbwWordEntity::class,
        WbwAudioTimingEntity::class,
        AtlasBundleEntity::class,
        AtlasWordShapeEntity::class,
    ],
    version = 4,
    exportSchema = false,
)
@ConstructedBy(ExternalQuranDatabaseConstructor::class)
abstract class ExternalQuranDatabase : RoomDatabase() {
    abstract fun wbwDao(): WbwDao
    abstract fun atlasWordShapeDao(): AtlasWordShapeDao
}

// The `actual` is generated by the Room compiler (KSP) for each target.
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpectedDeclaration")
expect object ExternalQuranDatabaseConstructor : RoomDatabaseConstructor<ExternalQuranDatabase> {
    override fun initialize(): ExternalQuranDatabase
}
