package com.cafarovceyxun.anamuslim.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.cafarovceyxun.anamuslim.db.dao.HadithDao
import com.cafarovceyxun.anamuslim.db.entities.hadith.*

@Database(
    entities = [
        HadithVolumeEntity::class,
        HadithBookEntity::class,
        HadithChapterEntity::class,
        HadithSubChapterEntity::class,
        HadithEntity::class
    ],
    version = 3,
    exportSchema = false,
)
@ConstructedBy(HadithDatabaseConstructor::class)
abstract class HadithDatabase : RoomDatabase() {
    abstract fun hadithDao(): HadithDao
}

// The `actual` is generated by the Room compiler (KSP) for each target.
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpectedDeclaration")
expect object HadithDatabaseConstructor : RoomDatabaseConstructor<HadithDatabase> {
    override fun initialize(): HadithDatabase
}
